-- ══════════════════════════════════════════════════════════════════
-- v23 — ai_tools (AI Tools Hub content table)
-- Run in: Supabase Dashboard → SQL Editor
--
-- FLAT type (no nested objects in the Tool interface — matches the
-- ai_glossary / blog_posts / nano_banana_custom_prompts precedent):
-- all fields are real columns, optional detail-page fields nullable.
-- ══════════════════════════════════════════════════════════════════

-- 1. Table
CREATE TABLE IF NOT EXISTS ai_tools (
  id                    TEXT        PRIMARY KEY,
  portal_id             TEXT        NOT NULL DEFAULT 'ai-academy',
  content_type          TEXT        NOT NULL DEFAULT 'tool',
  status                TEXT        NOT NULL DEFAULT 'published'
                                    CHECK (status IN ('published','draft','archived')),
  featured              BOOLEAN     NOT NULL DEFAULT false,
  sort_order            INT         NOT NULL DEFAULT 0,
  category              TEXT        NOT NULL DEFAULT '',
  name                  TEXT        NOT NULL,
  short_description_ar  TEXT        NOT NULL DEFAULT '',
  short_description_en  TEXT        NOT NULL DEFAULT '',
  use_cases             TEXT[]      NOT NULL DEFAULT '{}',
  level                 TEXT        NOT NULL DEFAULT 'beginner'
                                    CHECK (level IN ('beginner','intermediate','advanced')),
  pricing_type          TEXT        NOT NULL DEFAULT 'freemium'
                                    CHECK (pricing_type IN ('free','freemium','paid','open-source')),
  best_for              TEXT        NOT NULL DEFAULT '',
  tags                  TEXT[]      NOT NULL DEFAULT '{}',
  website               TEXT,
  -- Optional detail-page fields (most tools leave these null; the detail
  -- page falls back to category/related-tools sections when absent)
  overview_ar           TEXT,
  overview_en           TEXT,
  how_to_start_ar       TEXT[],
  how_to_start_en       TEXT[],
  pros                  TEXT[],
  limitations           TEXT[],
  alternatives          TEXT[],
  related_prompts       TEXT[],
  related_courses       TEXT[],
  recommended_path      TEXT,
  created_by            UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at          TIMESTAMPTZ,
  archived_at           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ai_tools_status   ON ai_tools (status);
CREATE INDEX IF NOT EXISTS idx_ai_tools_category ON ai_tools (category);

-- 2. Auto-update updated_at
CREATE OR REPLACE FUNCTION update_ai_tools_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_ai_tools_updated_at ON ai_tools;
CREATE TRIGGER trg_ai_tools_updated_at
  BEFORE UPDATE ON ai_tools
  FOR EACH ROW EXECUTE FUNCTION update_ai_tools_updated_at();

-- 3. RLS
ALTER TABLE ai_tools ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_published_ai_tools" ON ai_tools;
CREATE POLICY "public_read_published_ai_tools"
  ON ai_tools FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "admin_manage_ai_tools" ON ai_tools;
CREATE POLICY "admin_manage_ai_tools"
  ON ai_tools FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

-- ══════════════════════════════════════════════════════════════════
-- 4. Seed — the 68 existing static tools (status='published', SAME
--    ids as src/data/tools.ts) so the DB holds the full set and the
--    Tools Hub renders identically to before migration.
--    sort_order = original array index × 10 (room to insert between).
-- ══════════════════════════════════════════════════════════════════
INSERT INTO ai_tools (id, portal_id, content_type, status, featured, sort_order,
  category, name, short_description_ar, short_description_en, use_cases, level,
  pricing_type, best_for, tags, website, overview_ar, overview_en, how_to_start_ar,
  how_to_start_en, pros, limitations, alternatives, related_prompts, related_courses,
  recommended_path, published_at)
VALUES
  ('chatgpt', 'ai-academy', 'tool', 'published', true, 0, 'AI Chatbots', 'ChatGPT', 'أشهر نموذج محادثة من OpenAI', 'The most popular conversational AI from OpenAI', ARRAY['Writing','Coding','Analysis','Q&A']::text[], 'beginner', 'freemium', 'General use', ARRAY['gpt','openai','chat']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('claude', 'ai-academy', 'tool', 'published', true, 10, 'AI Chatbots', 'Claude', 'نموذج AI متقدم من Anthropic للمهام المعقدة', 'Advanced AI from Anthropic for complex tasks', ARRAY['Coding','Writing','Research','Analysis']::text[], 'beginner', 'freemium', 'Deep analysis', ARRAY['anthropic','claude']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('gemini', 'ai-academy', 'tool', 'published', false, 20, 'AI Chatbots', 'Gemini', 'نموذج AI متعدد الوسائط من Google', 'Multimodal AI from Google', ARRAY['Research','Coding','Multimodal']::text[], 'beginner', 'freemium', 'Google Workspace', ARRAY['google','gemini']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('perplexity', 'ai-academy', 'tool', 'published', true, 30, 'AI Chatbots', 'Perplexity', 'محرك بحث AI مع مصادر حقيقية', 'AI search engine with real sources', ARRAY['Research','Search','Citations']::text[], 'beginner', 'freemium', 'Research', ARRAY['search','research']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('copilot', 'ai-academy', 'tool', 'published', false, 40, 'AI Chatbots', 'Microsoft Copilot', 'مساعد AI مدمج في منتجات Microsoft', 'AI assistant integrated into Microsoft products', ARRAY['Office','Coding','Search']::text[], 'beginner', 'freemium', 'Microsoft 365', ARRAY['microsoft','office']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('claude-code', 'ai-academy', 'tool', 'published', true, 50, 'Claude Ecosystem', 'Claude Code', 'أداة برمجة AI متقدمة من Anthropic في الطرفية', 'Anthropic''s advanced CLI coding AI agent', ARRAY['Coding','Refactoring','Testing','Docs']::text[], 'intermediate', 'paid', 'Full-stack dev', ARRAY['claude','coding','cli']::text[], NULL, 'Claude Code هو وكيل AI متكامل يعمل مباشرة في طرفيتك. يمكنه قراءة وكتابة وتشغيل واختبار الكود تلقائياً، ويفهم هيكل مشروعك الكامل.', 'Claude Code is a full AI agent that works directly in your terminal. It can read, write, run, and test code automatically while understanding your entire project structure.', ARRAY['تثبيت npm install -g @anthropic-ai/claude-code','التشغيل بأمر claude في أي مجلد','قول ''build me a...'' وانتظر السحر']::text[], ARRAY['Install with npm install -g @anthropic-ai/claude-code','Run with claude command in any folder','Say ''build me a...'' and watch the magic']::text[], ARRAY['يفهم المشروع كاملاً','يكتب ويشغل الكود تلقائياً','يصلح الأخطاء بشكل ذاتي','يكتب الاختبارات']::text[], ARRAY['مدفوع (Claude Pro/Max)','يحتاج اتصال إنترنت','قد يرتكب أخطاء في مشاريع كبيرة جداً']::text[], ARRAY['Cursor','GitHub Copilot','Windsurf']::text[], ARRAY['build-website','audit-codebase','fix-bug']::text[], ARRAY['claude-mastery']::text[], 'claude-power-user', now()),
  ('claude-api', 'ai-academy', 'tool', 'published', true, 60, 'Claude Ecosystem', 'Claude API', 'API الرسمي للوصول البرمجي لنماذج Claude', 'Official API for programmatic access to Claude', ARRAY['API','Integration','Automation']::text[], 'advanced', 'paid', 'Developers', ARRAY['api','anthropic']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('mcp-servers', 'ai-academy', 'tool', 'published', true, 70, 'Claude Ecosystem', 'MCP Servers', 'بروتوكول Model Context لتوسيع قدرات Claude', 'Model Context Protocol to extend Claude''s abilities', ARRAY['Integration','Tools','Automation']::text[], 'advanced', 'open-source', 'Power users', ARRAY['mcp','protocol']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('claude-projects', 'ai-academy', 'tool', 'published', false, 80, 'Claude Ecosystem', 'Claude Projects', 'إدارة المشاريع مع Claude بسياق مثابر', 'Manage projects with Claude with persistent context', ARRAY['Projects','Context','Collaboration']::text[], 'intermediate', 'freemium', 'Project mgmt', ARRAY['claude','projects']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('claude-artifacts', 'ai-academy', 'tool', 'published', false, 90, 'Claude Ecosystem', 'Claude Artifacts', 'توليد وتشغيل الكود والمحتوى مباشرة في Claude', 'Generate and run code/content directly in Claude', ARRAY['Prototyping','UI','Coding']::text[], 'beginner', 'freemium', 'Rapid prototyping', ARRAY['claude','artifacts']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('github-copilot', 'ai-academy', 'tool', 'published', true, 100, 'Coding Agents', 'GitHub Copilot', 'مساعد البرمجة AI من GitHub مدمج في IDE', 'GitHub''s AI coding assistant integrated in IDEs', ARRAY['Autocomplete','Coding','Testing']::text[], 'beginner', 'paid', 'IDE users', ARRAY['github','copilot']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('cursor', 'ai-academy', 'tool', 'published', true, 110, 'Coding Agents', 'Cursor', 'محرر كود مبني بالكامل حول AI', 'IDE built entirely around AI coding', ARRAY['Coding','Refactoring','Debugging']::text[], 'intermediate', 'freemium', 'AI-first coding', ARRAY['cursor','ide']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('windsurf', 'ai-academy', 'tool', 'published', false, 120, 'Coding Agents', 'Windsurf', 'محرر AI من Codeium مع تدفق عمل متكامل', 'Codeium''s AI editor with integrated workflow', ARRAY['Coding','Automation','Refactoring']::text[], 'intermediate', 'freemium', 'Flow state coding', ARRAY['windsurf','ide']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('replit-agent', 'ai-academy', 'tool', 'published', false, 130, 'Coding Agents', 'Replit Agent', 'بناء تطبيقات كاملة بالمحادثة على Replit', 'Build full apps via conversation on Replit', ARRAY['Prototyping','Full-stack','Deployment']::text[], 'beginner', 'freemium', 'Quick prototypes', ARRAY['replit','agent']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('aider', 'ai-academy', 'tool', 'published', false, 140, 'Coding Agents', 'Aider', 'مساعد برمجة AI في الطرفية مفتوح المصدر', 'Open-source AI coding assistant in the terminal', ARRAY['Coding','Refactoring','Git']::text[], 'advanced', 'open-source', 'Terminal lovers', ARRAY['aider','cli']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('midjourney', 'ai-academy', 'tool', 'published', true, 150, 'Image Generation', 'Midjourney', 'أشهر أداة توليد صور AI عبر Discord', 'Most popular AI image generator via Discord', ARRAY['Art','Design','Marketing']::text[], 'beginner', 'paid', 'Art creation', ARRAY['image','art']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('dalle', 'ai-academy', 'tool', 'published', false, 160, 'Image Generation', 'DALL·E', 'مولد صور AI من OpenAI مع تحكم دقيق', 'OpenAI''s image generator with precise control', ARRAY['Images','Marketing','Content']::text[], 'beginner', 'paid', 'Quick visuals', ARRAY['dalle','openai']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('stable-diffusion', 'ai-academy', 'tool', 'published', false, 170, 'Image Generation', 'Stable Diffusion', 'مولد صور AI مفتوح المصدر يعمل محليًا', 'Open-source AI image generator running locally', ARRAY['Local AI','Custom Models','Art']::text[], 'advanced', 'open-source', 'Local generation', ARRAY['sd','local']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('ideogram', 'ai-academy', 'tool', 'published', false, 180, 'Image Generation', 'Ideogram', 'مولد صور AI ممتاز للنصوص داخل الصور', 'AI image generator excellent at text in images', ARRAY['Text Design','Logos','Marketing']::text[], 'beginner', 'freemium', 'Text in images', ARRAY['ideogram','text']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('n8n', 'ai-academy', 'tool', 'published', true, 190, 'AI Automation', 'n8n', 'منصة أتمتة مفتوحة المصدر قابلة للاستضافة الذاتية', 'Open-source automation platform, self-hostable', ARRAY['Workflows','Integration','AI Agents']::text[], 'intermediate', 'open-source', 'Developers', ARRAY['n8n','automation']::text[], NULL, 'n8n هي منصة أتمتة مفتوحة المصدر تتيح لك بناء سير عمل معقدة تربط مئات التطبيقات مع AI. يمكن استضافتها ذاتياً للحفاظ على الخصوصية.', 'n8n is an open-source automation platform that lets you build complex workflows connecting hundreds of apps with AI. It can be self-hosted for privacy.', ARRAY['تثبيت npm install -g n8n','تشغيل n8n في المحطة الطرفية','فتح localhost:5678 وبدء بناء أول سير عمل']::text[], ARRAY['Install npm install -g n8n','Run n8n in terminal','Open localhost:5678 and start building first workflow']::text[], ARRAY['مفتوح المصدر ومجاني للاستضافة الذاتية','أكثر من 400 تكامل','مرن جداً','دعم AI Agents']::text[], ARRAY['يحتاج خبرة تقنية','الاستضافة السحابية مدفوعة','المستندات أقل شمولاً من Zapier']::text[], ARRAY['Make','Zapier','Activepieces']::text[], ARRAY['automation-workflow']::text[], ARRAY['ai-automation']::text[], 'ai-developer', now()),
  ('make', 'ai-academy', 'tool', 'published', false, 200, 'AI Automation', 'Make', 'منصة أتمتة بصرية سهلة الاستخدام', 'Visual automation platform easy to use', ARRAY['No-code','Workflows','Integration']::text[], 'beginner', 'freemium', 'No-code users', ARRAY['make','nocode']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('zapier', 'ai-academy', 'tool', 'published', false, 210, 'AI Automation', 'Zapier', 'منصة الأتمتة الأكثر شعبية مع آلاف التكاملات', 'Most popular automation platform with thousands of integrations', ARRAY['No-code','Automation','SaaS']::text[], 'beginner', 'freemium', 'Business automation', ARRAY['zapier','saas']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('ollama', 'ai-academy', 'tool', 'published', true, 220, 'Local LLMs', 'Ollama', 'تشغيل نماذج LLM محليًا بأمر واحد', 'Run LLM models locally with one command', ARRAY['Local AI','Privacy','Offline']::text[], 'intermediate', 'open-source', 'Local AI', ARRAY['ollama','local']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('lm-studio', 'ai-academy', 'tool', 'published', true, 230, 'Local LLMs', 'LM Studio', 'واجهة رسومية لتشغيل وإدارة النماذج المحلية', 'GUI for running and managing local models', ARRAY['Local AI','GUI','Model Management']::text[], 'beginner', 'free', 'GUI users', ARRAY['lmstudio','gui']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('open-webui', 'ai-academy', 'tool', 'published', false, 240, 'Local LLMs', 'Open WebUI', 'واجهة ويب مفتوحة لـ Ollama والنماذج المحلية', 'Open web interface for Ollama and local models', ARRAY['UI','Local AI','Ollama']::text[], 'beginner', 'open-source', 'Web interface', ARRAY['openwebui','ui']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('jupyter', 'ai-academy', 'tool', 'published', false, 250, 'Data Analysis', 'Jupyter Notebooks', 'بيئة تطوير تفاعلية للبيانات والـ ML', 'Interactive development environment for data and ML', ARRAY['Data Science','ML','Research']::text[], 'beginner', 'open-source', 'Data science', ARRAY['jupyter','python']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('colab', 'ai-academy', 'tool', 'published', true, 260, 'Data Analysis', 'Google Colab', 'Jupyter مجاني في السحاب مع GPU من Google', 'Free Jupyter in the cloud with Google GPU', ARRAY['Free GPU','ML','Training']::text[], 'beginner', 'free', 'Free GPU', ARRAY['colab','google']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('notebooklm', 'ai-academy', 'tool', 'published', true, 270, 'AI Search', 'NotebookLM', 'مساعد بحث AI من Google مع مصادرك الخاصة', 'Google''s AI research assistant with your own sources', ARRAY['Research','Podcasts','Analysis']::text[], 'beginner', 'free', 'Research', ARRAY['google','research']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('v0', 'ai-academy', 'tool', 'published', true, 280, 'Design AI', 'v0 by Vercel', 'توليد واجهات مستخدم React من وصف نصي', 'Generate React UIs from text description', ARRAY['UI Generation','React','Prototyping']::text[], 'beginner', 'freemium', 'UI generation', ARRAY['v0','ui','react']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('figma-ai', 'ai-academy', 'tool', 'published', false, 290, 'Design AI', 'Figma AI', 'ميزات AI مدمجة في Figma للتصميم الأسرع', 'Built-in AI features in Figma for faster design', ARRAY['Design','Prototyping','Collaboration']::text[], 'beginner', 'freemium', 'Designers', ARRAY['figma','design']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('canva-ai', 'ai-academy', 'tool', 'published', false, 300, 'Design AI', 'Canva AI', 'تصميم بالذكاء الاصطناعي للجميع', 'AI-powered design for everyone', ARRAY['Design','Social','Marketing']::text[], 'beginner', 'freemium', 'Non-designers', ARRAY['canva','design']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('elevenlabs', 'ai-academy', 'tool', 'published', true, 310, 'Voice & Audio', 'ElevenLabs', 'توليد صوت AI واقعي بأصوات متعددة', 'Realistic AI voice generation with multiple voices', ARRAY['TTS','Cloning','Content']::text[], 'beginner', 'freemium', 'Voice content', ARRAY['tts','voice']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('whisper', 'ai-academy', 'tool', 'published', false, 320, 'Voice & Audio', 'OpenAI Whisper', 'تحويل الكلام إلى نص مفتوح المصدر من OpenAI', 'Open-source speech-to-text from OpenAI', ARRAY['Transcription','Translation','STT']::text[], 'intermediate', 'open-source', 'Transcription', ARRAY['whisper','stt']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('aws-bedrock', 'ai-academy', 'tool', 'published', true, 330, 'Cloud AI', 'AWS Bedrock', 'خدمة نماذج AI مُدارة من Amazon Web Services', 'Managed AI model service from Amazon Web Services', ARRAY['LLMs','AWS','Enterprise']::text[], 'advanced', 'paid', 'AWS users', ARRAY['aws','bedrock']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('vertex-ai', 'ai-academy', 'tool', 'published', false, 340, 'Cloud AI', 'Google Vertex AI', 'منصة ML وAI المُدارة من Google Cloud', 'Managed ML and AI platform from Google Cloud', ARRAY['MLOps','Training','Serving']::text[], 'advanced', 'paid', 'GCP users', ARRAY['vertex','google']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('azure-openai', 'ai-academy', 'tool', 'published', false, 350, 'Cloud AI', 'Azure OpenAI', 'نماذج OpenAI على البنية التحتية لـ Azure', 'OpenAI models on Azure infrastructure', ARRAY['Enterprise','Compliance','Integration']::text[], 'advanced', 'paid', 'Enterprise', ARRAY['azure','openai']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('vercel', 'ai-academy', 'tool', 'published', true, 360, 'Deployment', 'Vercel', 'أسهل منصة نشر لتطبيقات Next.js وFrontend', 'Easiest deployment platform for Next.js and Frontend', ARRAY['Deployment','Frontend','CI/CD']::text[], 'beginner', 'freemium', 'Frontend apps', ARRAY['vercel','deploy']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('cloudflare', 'ai-academy', 'tool', 'published', false, 370, 'Deployment', 'Cloudflare Pages', 'نشر مواقع ثابتة وعمال الحافة من Cloudflare', 'Static sites and edge workers deployment from Cloudflare', ARRAY['Static','Edge','CDN']::text[], 'beginner', 'freemium', 'Static sites', ARRAY['cloudflare','cdn']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('supabase', 'ai-academy', 'tool', 'published', true, 380, 'Databases & Backend', 'Supabase', 'قاعدة بيانات Postgres مع Auth وStorage وEdge Functions', 'Postgres DB with Auth, Storage, and Edge Functions', ARRAY['Database','Auth','Storage','API']::text[], 'intermediate', 'freemium', 'Full-stack', ARRAY['supabase','postgres']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('langchain', 'ai-academy', 'tool', 'published', true, 390, 'AI Frameworks', 'LangChain', 'إطار بناء تطبيقات LLM والوكلاء الذكيين', 'Framework for building LLM apps and AI agents', ARRAY['Agents','RAG','Chains','Tools']::text[], 'intermediate', 'open-source', 'LLM apps', ARRAY['langchain','llm']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('llamaindex', 'ai-academy', 'tool', 'published', false, 400, 'AI Frameworks', 'LlamaIndex', 'إطار بناء محركات RAG وبحث البيانات', 'Framework for building RAG and data search engines', ARRAY['RAG','Search','Indexing']::text[], 'intermediate', 'open-source', 'RAG systems', ARRAY['llamaindex','rag']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('chroma', 'ai-academy', 'tool', 'published', false, 410, 'Vector Databases', 'Chroma', 'قاعدة بيانات متجهية مفتوحة المصدر خفيفة للبدء', 'Lightweight open-source vector database to get started', ARRAY['RAG','Embeddings','Local']::text[], 'intermediate', 'open-source', 'Getting started', ARRAY['chroma','vector']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('pinecone', 'ai-academy', 'tool', 'published', true, 420, 'Vector Databases', 'Pinecone', 'قاعدة بيانات متجهية سحابية عالية الأداء', 'High-performance cloud vector database', ARRAY['Production','RAG','Scale']::text[], 'advanced', 'freemium', 'Production RAG', ARRAY['pinecone','cloud']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('notion-ai', 'ai-academy', 'tool', 'published', false, 430, 'Productivity AI', 'Notion AI', 'مساعد AI مدمج في Notion للكتابة والتلخيص', 'AI assistant built into Notion for writing and summaries', ARRAY['Writing','Notes','Planning']::text[], 'beginner', 'paid', 'Knowledge workers', ARRAY['notion','ai']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('gamma', 'ai-academy', 'tool', 'published', false, 440, 'Productivity AI', 'Gamma', 'إنشاء عروض تقديمية احترافية بالذكاء الاصطناعي', 'Create professional presentations with AI', ARRAY['Presentations','Docs','Content']::text[], 'beginner', 'freemium', 'Presentations', ARRAY['gamma','slides']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('mem', 'ai-academy', 'tool', 'published', false, 450, 'Productivity AI', 'Mem', 'مساعد ملاحظات AI يُنظم معلوماتك تلقائياً', 'AI note assistant that auto-organizes your knowledge', ARRAY['Notes','PKM','Research']::text[], 'beginner', 'freemium', 'Knowledge mgmt', ARRAY['mem','notes','pkm']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('grok', 'ai-academy', 'tool', 'published', false, 460, 'AI Chatbots', 'Grok', 'نموذج AI من xAI بوصول فوري لأخبار X/Twitter', 'xAI''s model with real-time X/Twitter access', ARRAY['Research','News','Chat','Humor']::text[], 'beginner', 'freemium', 'Real-time info', ARRAY['grok','xai','x']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('mistral', 'ai-academy', 'tool', 'published', false, 470, 'AI Chatbots', 'Mistral Chat', 'نموذج LLM أوروبي مفتوح المصدر عالي الكفاءة', 'High-efficiency European open-source LLM', ARRAY['Chat','Coding','Privacy']::text[], 'intermediate', 'freemium', 'Privacy-first', ARRAY['mistral','llm']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('deepseek', 'ai-academy', 'tool', 'published', false, 480, 'AI Chatbots', 'DeepSeek', 'نموذج AI صيني مفتوح المصدر بأداء مذهل مجاناً', 'Open-source Chinese AI model with impressive free performance', ARRAY['Coding','Math','Research']::text[], 'beginner', 'free', 'Free coding AI', ARRAY['deepseek','llm']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('runway-ml', 'ai-academy', 'tool', 'published', true, 490, 'Video AI', 'Runway ML', 'توليد وتحرير فيديو AI احترافي من النص أو الصور', 'Professional AI video generation and editing from text or images', ARRAY['Video Gen','Editing','VFX']::text[], 'intermediate', 'freemium', 'AI video', ARRAY['runway','video','ai']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('pika', 'ai-academy', 'tool', 'published', false, 500, 'Video AI', 'Pika', 'تحويل النص أو الصور إلى فيديو AI بجودة عالية', 'Transform text or images into high-quality AI video', ARRAY['Text2Video','Image2Video','Animation']::text[], 'beginner', 'freemium', 'Quick videos', ARRAY['pika','video']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('kling', 'ai-academy', 'tool', 'published', false, 510, 'Video AI', 'Kling AI', 'نموذج توليد فيديو AI من Kuaishou بجودة سينمائية', 'Kuaishou''s cinematic AI video generation model', ARRAY['Video Gen','Cinematic','Motion']::text[], 'intermediate', 'freemium', 'Cinematic video', ARRAY['kling','video']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('luma-dream', 'ai-academy', 'tool', 'published', false, 520, 'Video AI', 'Luma Dream Machine', 'توليد فيديوهات فوتوريالستية بالذكاء الاصطناعي', 'Generate photorealistic AI videos from text prompts', ARRAY['3D Video','Photorealistic','Motion']::text[], 'beginner', 'freemium', 'Photorealistic', ARRAY['luma','video']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('suno', 'ai-academy', 'tool', 'published', true, 530, 'AI Music', 'Suno', 'توليد أغانٍ كاملة باللحن والكلمات بالذكاء الاصطناعي', 'Generate complete songs with melody and lyrics using AI', ARRAY['Music Gen','Lyrics','Songs']::text[], 'beginner', 'freemium', 'Full songs', ARRAY['suno','music','ai']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('udio', 'ai-academy', 'tool', 'published', false, 540, 'AI Music', 'Udio', 'توليد موسيقى AI بجودة استوديو من وصف نصي', 'Studio-quality AI music generation from text descriptions', ARRAY['Music Gen','Audio','Composition']::text[], 'beginner', 'freemium', 'Music creation', ARRAY['udio','music']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('bolt-new', 'ai-academy', 'tool', 'published', true, 550, 'Coding Agents', 'Bolt.new', 'بناء تطبيقات ويب كاملة في المتصفح بمحادثة واحدة', 'Build full-stack web apps in the browser via conversation', ARRAY['Full-stack','Prototyping','No-code']::text[], 'beginner', 'freemium', 'Instant apps', ARRAY['bolt','web','nocode']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('lovable', 'ai-academy', 'tool', 'published', false, 560, 'Coding Agents', 'Lovable', 'منصة AI لبناء تطبيقات React بسرعة قياسية', 'AI platform for building React apps at record speed', ARRAY['React','Full-stack','Startups']::text[], 'beginner', 'freemium', 'Startup MVPs', ARRAY['lovable','react']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('jasper', 'ai-academy', 'tool', 'published', false, 570, 'AI Writing', 'Jasper AI', 'منصة كتابة محتوى تسويقي AI للشركات', 'AI marketing content writing platform for businesses', ARRAY['Marketing','Copywriting','SEO','Blog']::text[], 'beginner', 'paid', 'Marketing copy', ARRAY['jasper','copy']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('grammarly-ai', 'ai-academy', 'tool', 'published', false, 580, 'AI Writing', 'Grammarly AI', 'مساعد كتابة AI لتحسين القواعد والأسلوب والنبرة', 'AI writing assistant for grammar, style, and tone', ARRAY['Grammar','Writing','Email','Clarity']::text[], 'beginner', 'freemium', 'Writing clarity', ARRAY['grammarly','write']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('consensus', 'ai-academy', 'tool', 'published', true, 590, 'AI Research', 'Consensus', 'محرك بحث AI يستخرج نتائج من الأوراق العلمية', 'AI search engine extracting findings from research papers', ARRAY['Research','Citations','Science']::text[], 'beginner', 'freemium', 'Academic research', ARRAY['consensus','papers']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('elicit', 'ai-academy', 'tool', 'published', false, 600, 'AI Research', 'Elicit', 'أداة AI لتحليل الأبحاث العلمية وتلخيصها تلقائياً', 'AI tool for automatically analyzing and summarizing scientific research', ARRAY['Research','Summarize','Papers']::text[], 'intermediate', 'freemium', 'Literature review', ARRAY['elicit','research']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('framer-ai', 'ai-academy', 'tool', 'published', false, 610, 'Design AI', 'Framer AI', 'بناء مواقع احترافية بالذكاء الاصطناعي مع تحكم كامل', 'Build professional websites with AI and full design control', ARRAY['Web Design','CMS','Landing Pages']::text[], 'beginner', 'freemium', 'Design-led sites', ARRAY['framer','design']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('huggingface', 'ai-academy', 'tool', 'published', true, 620, 'AI Frameworks', 'Hugging Face', 'أكبر مستودع لنماذج AI ومجموعات البيانات مفتوحة المصدر', 'The largest open-source hub for AI models, datasets and spaces', ARRAY['Models','Datasets','Spaces','Research']::text[], 'intermediate', 'freemium', 'Open models', ARRAY['huggingface','models','hub']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('openrouter', 'ai-academy', 'tool', 'published', false, 630, 'AI Chatbots', 'OpenRouter', 'بوابة موحدة للوصول لأكثر من 100 نموذج AI بـ API واحد', 'Unified gateway to 100+ AI models via a single API', ARRAY['Multi-model','API','Cost','Comparison']::text[], 'intermediate', 'freemium', 'Model comparison', ARRAY['openrouter','api','models']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('google-ai-studio', 'ai-academy', 'tool', 'published', false, 640, 'AI Chatbots', 'Google AI Studio', 'مساحة تجربة Gemini المجانية مع وصول مباشر للـ API والاختبار', 'Free Gemini playground with direct API access and testing', ARRAY['API Testing','Gemini','Prototyping']::text[], 'beginner', 'free', 'Gemini API', ARRAY['google','gemini','studio']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('flux-image', 'ai-academy', 'tool', 'published', false, 650, 'Image Generation', 'FLUX.1', 'نموذج توليد صور مفتوح المصدر بجودة استثنائية من Black Forest Labs', 'State-of-the-art open-source image generation by Black Forest Labs', ARRAY['Image Gen','Fine-tuning','Open-source']::text[], 'intermediate', 'open-source', 'Quality + open', ARRAY['flux','image','open-source']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('warp', 'ai-academy', 'tool', 'published', false, 660, 'Coding Agents', 'Warp Terminal', 'طرفية برمجية مبنية لعصر AI مع إكمال ذكي ومشاركة الأوامر', 'AI-native terminal with smart completion and command sharing', ARRAY['Terminal','AI Commands','Productivity']::text[], 'beginner', 'freemium', 'AI terminal', ARRAY['warp','terminal','cli']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now()),
  ('beautiful-ai', 'ai-academy', 'tool', 'published', false, 670, 'Productivity AI', 'Beautiful.ai', 'عروض تقديمية ذكية تتنسّق تلقائياً بمساعدة الذكاء الاصطناعي', 'Smart AI presentations that auto-format and adapt on their own', ARRAY['Presentations','Slides','Auto-design']::text[], 'beginner', 'freemium', 'Auto-design slides', ARRAY['beautiful','slides','design']::text[], NULL, NULL, NULL, '{}', '{}', '{}', '{}', '{}', '{}', '{}', NULL, now());
