-- ═════════════════════════════════════════════════════════════════
-- v38 — Automation Curated Workflow Library (automation_workflows) — HYBRID: workflow_map_nodes + cleaned_json JSONB
-- Run in: Supabase Dashboard → SQL Editor
-- ═════════════════════════════════════════════════════════════════

-- 1. Table
CREATE TABLE IF NOT EXISTS automation_workflows (
  id                      TEXT        PRIMARY KEY,
  portal_id               TEXT        NOT NULL DEFAULT 'automation',
  content_type            TEXT        NOT NULL DEFAULT 'workflow',
  status                  TEXT        NOT NULL DEFAULT 'published'
                                      CHECK (status IN ('published','draft','archived')),
  featured                BOOLEAN     NOT NULL DEFAULT false,
  sort_order              INT         NOT NULL DEFAULT 0,
  title                  TEXT NOT NULL DEFAULT '',
  category               TEXT NOT NULL DEFAULT '',
  department             TEXT NOT NULL DEFAULT '',
  difficulty             TEXT NOT NULL DEFAULT 'مبتدئ',
  business_problem       TEXT NOT NULL DEFAULT '',
  workflow_summary       TEXT NOT NULL DEFAULT '',
  required_tools         TEXT[] NOT NULL DEFAULT '{}',
  setup_steps            TEXT[] NOT NULL DEFAULT '{}',
  input_fields           TEXT[] NOT NULL DEFAULT '{}',
  output                 TEXT NOT NULL DEFAULT '',
  testing_checklist      TEXT[] NOT NULL DEFAULT '{}',
  risks                  TEXT[] NOT NULL DEFAULT '{}',
  upgrade_ideas          TEXT[] NOT NULL DEFAULT '{}',
  estimated_setup_time   TEXT NOT NULL DEFAULT '',
  access                 TEXT NOT NULL DEFAULT 'Free',
  trigger_label          TEXT NOT NULL DEFAULT '',
  actions                TEXT[] NOT NULL DEFAULT '{}',
  short_description      TEXT NOT NULL DEFAULT '',
  business_value         TEXT NOT NULL DEFAULT '',
  required_accounts      TEXT[] NOT NULL DEFAULT '{}',
  credentials_guide      TEXT NOT NULL DEFAULT '',
  node_count             INT NOT NULL DEFAULT 0,
  tags                   TEXT[] NOT NULL DEFAULT '{}',
  seo_hashtags           TEXT[] NOT NULL DEFAULT '{}',
  industry               TEXT NOT NULL DEFAULT '',
  trigger_type           TEXT NOT NULL DEFAULT '',
  integrations           TEXT[] NOT NULL DEFAULT '{}',
  has_cleaned_json       BOOLEAN NOT NULL DEFAULT false,
  json_file_name         TEXT NOT NULL DEFAULT '',
  related_template_ids   TEXT[] NOT NULL DEFAULT '{}',
  related_lab_ids        TEXT[] NOT NULL DEFAULT '{}',
  related_checklist_ids  TEXT[] NOT NULL DEFAULT '{}',
  common_mistakes        TEXT[] NOT NULL DEFAULT '{}',
  safety_status          TEXT NOT NULL DEFAULT '',
  safety_notes           TEXT NOT NULL DEFAULT '',
  visible                BOOLEAN NOT NULL DEFAULT true,
  workflow_map_nodes     JSONB NOT NULL DEFAULT '[]'::jsonb,
  cleaned_json           JSONB,
  created_by              UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_at             TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_automation_workflows_status ON automation_workflows (status);

-- 2. Auto-update updated_at
CREATE OR REPLACE FUNCTION update_automation_workflows_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_automation_workflows_updated_at ON automation_workflows;
CREATE TRIGGER trg_automation_workflows_updated_at
  BEFORE UPDATE ON automation_workflows
  FOR EACH ROW EXECUTE FUNCTION update_automation_workflows_updated_at();

-- 3. RLS
ALTER TABLE automation_workflows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_published_automation_workflows" ON automation_workflows;
CREATE POLICY "public_read_published_automation_workflows"
  ON automation_workflows FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "admin_manage_automation_workflows" ON automation_workflows;
CREATE POLICY "admin_manage_automation_workflows"
  ON automation_workflows FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- Service role (API routes using createAdminClient) bypasses RLS — application
-- code verifies admin role before writes, matching existing tables' convention.

-- ═════════════════════════════════════════════════════════════════
-- 4. Seed — the existing static 30 workflow entries, SAME ids,
--    status='published'. Generated programmatically from the real TS source
--    (zero transcription risk). Static array remains as fallback only.
-- ═════════════════════════════════════════════════════════════════
INSERT INTO automation_workflows (id, portal_id, content_type, status, featured, sort_order, title, category, department, difficulty, business_problem, workflow_summary, required_tools, setup_steps, input_fields, output, testing_checklist, risks, upgrade_ideas, estimated_setup_time, access, trigger_label, actions, short_description, business_value, required_accounts, credentials_guide, node_count, tags, seo_hashtags, industry, trigger_type, integrations, has_cleaned_json, json_file_name, related_template_ids, related_lab_ids, related_checklist_ids, common_mistakes, safety_status, safety_notes, visible, workflow_map_nodes, cleaned_json, published_at)
VALUES
  ('student-welcome-flow', 'automation', 'workflow', 'published', true, 0, 'ترحيب الطلاب بعد التسجيل', 'Education Automation', 'education', 'مبتدئ', 'المركز التعليمي يهدر وقتًا في إرسال رسائل البداية يدويًا.', 'استلام تسجيل جديد ثم إرسال رسالة ترحيب وبريد وفتح سجل متابعة تلقائي.', ARRAY['Google Forms','Google Sheets','Gmail'], ARRAY['ربط النموذج بالجدول','إنشاء قالب رسالة الترحيب','إضافة خطوة تحديث السجل','إعداد إشعار للمنسق'], ARRAY['اسم الطالب','البريد','رقم الهاتف','اسم الدورة'], 'رسالة ترحيب + سجل طالب محدث + إشعار داخلي.', ARRAY['اختبر تسجيل طالب وهمي','تأكد من تحديث السجل','تحقق من وصول الرسالة'], ARRAY['تكرار التسجيل','أرقام واتساب غير صحيحة'], ARRAY['إضافة تذكير بالجلسة الأولى','ربطها بنظام الشهادات لاحقًا'], '45 دقيقة', 'Free', 'New form submission', ARRAY['Send email','Send WhatsApp message','Add row'], 'أرسل رسالة ترحيب تلقائية لكل طالب جديد وافتح سجله فورًا.', 'توفير 2–3 ساعات أسبوعيًا وتحسين انطباع الطالب الأول.', ARRAY['Google Workspace أو حساب Gmail'], '', 4, ARRAY['تعليم','ترحيب','طلاب','Gmail','Google Forms'], ARRAY['#n8n','#automation','#تعليم','#GoogleForms','#workflow'], 'التعليم', 'Webhook / Form', ARRAY['Google Forms','Gmail','Google Sheets'], false, '', ARRAY['course-registration-pipeline','pdf-certificates'], ARRAY['lab-google-forms-trigger'], '{}', ARRAY['نسيان ربط النموذج بالـ trigger','حقول غير متطابقة بين النموذج والـ sheet'], 'آمن', 'لا توجد بيانات حساسة. يُستخدم فقط بيانات التسجيل العامة.', true, '[]'::jsonb, NULL, now()),
  ('google-form-to-crm', 'automation', 'workflow', 'published', true, 10, 'Google Form إلى CRM — خط leads تلقائي', 'CRM & Sales', 'sales', 'مبتدئ', 'الـ leads تصل من forms ثم تضيع قبل إدخالها يدويًا.', 'كل submission يخلق lead جديدًا مع owner ومرحلة أولية.', ARRAY['Google Forms','CRM (HubSpot / Notion / Airtable)','Gmail'], ARRAY['تحديد الحقول المطلوبة في النموذج','مطابقة الحقول مع CRM','إضافة تنبيه للبائع المسؤول'], ARRAY['الاسم','الهاتف','البريد','المصدر'], 'lead جديد داخل CRM مع إشعار متابعة.', ARRAY['أرسل تسجيل تجريبي','تحقق من ظهور الـ lead في CRM','تأكد من وصول إشعار البائع'], ARRAY['تكرار الـ leads','leads بلا owner'], ARRAY['إضافة lead scoring','إضافة WhatsApp follow-up تلقائي'], '35 دقيقة', 'Free', 'New form submission', ARRAY['Update CRM','Send email'], 'حوّل كل submission من نموذج Google تلقائيًا إلى lead داخل CRM مع إشعار البائع.', 'لا تضيع أي فرصة بيع — كل lead يدخل CRM في ثوانٍ.', ARRAY['Google Workspace','حساب CRM'], '', 4, ARRAY['CRM','leads','مبيعات','Google Forms','HubSpot'], ARRAY['#CRM','#n8n','#automation','#مبيعات','#leads'], 'المبيعات', 'Webhook / Form', ARRAY['Google Forms','HubSpot','Gmail'], false, '', ARRAY['lead-followup-whatsapp','website-lead-to-whatsapp'], '{}', '{}', ARRAY['تطابق غير صحيح للحقول','نسيان تعيين owner للـ lead'], 'آمن', 'بيانات العملاء عامة. تأكد من عدم تخزين بيانات دفع في النموذج.', true, '[]'::jsonb, NULL, now()),
  ('daily-ai-email-brief', 'automation', 'workflow', 'published', true, 20, 'موجز بريد يومي بالذكاء الاصطناعي', 'AI Agents', 'operations', 'متوسط', 'المدير لا يستطيع مراجعة عشرات الرسائل يوميًا بفعالية.', 'جمع رسائل محددة وتوليد brief عربي مع أهم القرارات.', ARRAY['Gmail','AI Model (Gemini / OpenAI)','Notion أو Google Docs'], ARRAY['اختر labels أو inbox rules للتصفية','أضف Gmail node بالصلاحيات المناسبة','أضف AI node مع prompt التلخيص','احفظ Brief في Notion أو أرسله إلى بريدك'], ARRAY['محتوى الرسائل','المرسل','الأولوية'], 'ملخص يومي مختصر مع إجراءات مقترحة.', ARRAY['فحص جودة التلخيص على رسائل حقيقية','تأكد من عدم تسريب محتوى حساس','اختبر الجدولة اليومية'], ARRAY['تلخيص غير دقيق','حساسية محتوى الرسائل'], ARRAY['إضافة تصنيف حسب المشروع','إرسال brief للإدارة العليا'], '50 دقيقة', 'Pro', 'Scheduled time', ARRAY['Fetch emails','AI summarize','Create document','Send summary'], 'لخّص بريدك اليومي تلقائيًا بالذكاء الاصطناعي واستقبل قرارات اليوم في رسالة واحدة.', 'ساعة+ يوميًا من وقت الإدارة محفوظة — قرارات أسرع وأوضح.', ARRAY['حساب Gmail','حساب Gemini أو OpenAI API'], 'احتفظ بـ API Key الخاص بك في n8n Credentials. لا تضعه داخل الـ workflow مباشرة.', 5, ARRAY['AI','Gmail','ذكاء اصطناعي','تلخيص','Gemini'], ARRAY['#AI','#n8n','#automation','#Gmail','#Gemini'], 'الإدارة والعمليات', 'Schedule', ARRAY['Gmail','Gemini API','Notion'], false, '', ARRAY['meeting-summary-distribution','weekly-sales-report'], '{}', '{}', ARRAY['prompt غير دقيق ينتج تلخيصًا ضعيفًا','نسيان إضافة Gmail OAuth scope'], 'يحتاج مراجعة', 'تتعامل هذه الأتمتة مع محتوى بريدك الإلكتروني. تأكد من استخدام OAuth ولا ترسل محتوى سري إلى AI خارجي دون موافقة.', true, '[]'::jsonb, NULL, now()),
  ('weekly-sales-report', 'automation', 'workflow', 'published', false, 30, 'تقرير المبيعات الأسبوعي التلقائي', 'Reporting & Dashboards', 'sales', 'متوسط', 'التقرير الأسبوعي يستهلك وقتًا يدويًا في السحب والتنسيق.', 'قراءة الأرقام من Sheet أو CRM ثم صياغة report وإرساله.', ARRAY['Google Sheets','CRM','Gmail أو Slack'], ARRAY['تحديد مصادر البيانات (Sheet أو CRM)','حساب المؤشرات الأساسية','تجهيز قالب التقرير','جدولة الإرسال كل يوم أحد'], ARRAY['إجمالي المبيعات','عدد الصفقات','الفرص المفتوحة'], 'تقرير PDF أو Email summary جاهز للإرسال.', ARRAY['مطابقة الأرقام مع المصدر','فحص آخر تحديث للبيانات','اختبار المرفقات'], ARRAY['بيانات غير محدّثة تعطي تقريرًا خاطئًا'], ARRAY['إضافة مقارنة شهرية','إدخال AI commentary على الأرقام'], '60 دقيقة', 'Service-ready', 'Scheduled time', ARRAY['Read sheet','Calculate KPIs','Format report','Send email'], 'اجمع أرقام المبيعات تلقائيًا كل أسبوع وأرسل تقريرًا منسّقًا لفريقك.', '3–4 ساعات أسبوعيًا محفوظة — تقرير منتظم لا يُنسى.', ARRAY['Google Workspace','CRM access'], '', 5, ARRAY['تقارير','مبيعات','Google Sheets','CRM','مؤشرات'], ARRAY['#reporting','#n8n','#automation','#مبيعات','#GoogleSheets'], 'المبيعات', 'Schedule', ARRAY['Google Sheets','Gmail','Slack'], false, '', ARRAY['daily-ai-email-brief','sales-pipeline-update'], '{}', '{}', ARRAY['مؤشرات ناقصة','تضارب مصادر البيانات'], 'آمن', 'البيانات داخلية. تأكد من عدم إرسال التقرير لجهات خارجية.', true, '[]'::jsonb, NULL, now()),
  ('lead-followup-whatsapp', 'automation', 'workflow', 'published', true, 40, 'متابعة Lead عبر واتساب تلقائيًا', 'CRM & Sales', 'sales', 'متوسط', 'العملاء المحتملون يبردون سريعًا إذا لم تصلهم متابعة واضحة.', 'بعد دخول lead جديد تُرسل رسالة approved ثم يُنشأ task للبائع.', ARRAY['CRM','WhatsApp Business API','Calendar أو Notion'], ARRAY['تحديد شروط إرسال الرسالة','ربط lead owner بالرسالة','ضبط تذكير follow-up','اختبار على رقم وهمي أولًا'], ARRAY['الاسم','الخدمة','المالك','الحالة'], 'رسالة متابعة أولية + تذكير داخلي.', ARRAY['اختبر القالب على رقم تجريبي','فحص حالة الإرسال','منع الإرسال خارج ساعات العمل'], ARRAY['قيود واتساب','رسائل مكررة تُزعج العميل'], ARRAY['إضافة lead scoring','إضافة handoff إلى مكالمة فيديو'], '55 دقيقة', 'Service-ready', 'New CRM lead', ARRAY['Send WhatsApp message','Create task','Notify owner'], 'أرسل رسالة واتساب أولية للـ lead الجديد فور دخوله CRM وأنشئ مهمة للبائع.', 'استجابة في دقائق بدلًا من ساعات — زيادة معدل التحويل.', ARRAY['حساب WhatsApp Business API (Twilio أو 360dialog)','CRM'], 'WhatsApp Business API يتطلب حساب موافَق من Meta. استخدم Twilio أو 360dialog كـ provider وأضف credentials في n8n.', 4, ARRAY['واتساب','leads','CRM','مبيعات','WhatsApp API'], ARRAY['#WhatsApp','#n8n','#automation','#CRM','#مبيعات'], 'المبيعات', 'Webhook', ARRAY['WhatsApp Business API','CRM','Twilio'], false, '', ARRAY['google-form-to-crm','website-lead-to-whatsapp'], '{}', '{}', ARRAY['إرسال رسائل مكررة','استخدام API غير موافَق'], 'يحتاج مراجعة', 'واتساب Business API يتطلب موافقة Meta. لا تستخدم WhatsApp شخصي. اختبر دائمًا قبل التفعيل الكامل.', true, '[]'::jsonb, NULL, now()),
  ('social-content-approval', 'automation', 'workflow', 'published', false, 50, 'مسار اعتماد المحتوى للسوشيال ميديا', 'Marketing Campaign Automation', 'marketing', 'متوسط', 'المنشورات تُنشر دون سلسلة اعتماد أو تتأخر بين الفرق.', 'إدخال المحتوى، مراجعة، اعتماد، ثم تسليم للنشر.', ARRAY['Notion','Slack','Make أو n8n'], ARRAY['إنشاء قاعدة محتوى في Notion','تحديد حالات workflow (مسودة / مراجعة / مُعتمَد / منشور)','ربط تنبيهات الاعتماد بـ Slack','اختبار دورة اعتماد كاملة'], ARRAY['عنوان المحتوى','القناة','المالك','موعد النشر'], 'سجل محتوى بحالات واضحة وإشعارات مراجعة.', ARRAY['تغيير الحالة من مسودة إلى مراجعة','تأكد من وصول إشعار المراجع','تحقق من منع تخطي الاعتماد'], ARRAY['نشر محتوى غير مُعتمَد','فقدان تاريخ المراجعة'], ARRAY['إضافة AI summary للمحتوى','ربطها بتقويم النشر'], '45 دقيقة', 'Pro', 'Manual button', ARRAY['Route approval','Notify reviewer','Update status','Deliver to publisher'], 'سلسلة اعتماد منظمة للمحتوى — من الكتابة إلى النشر بدون فوضى.', 'محتوى مُعتمَد بانتظام دون اجتماعات لا نهاية لها.', ARRAY['Notion Workspace','Slack Workspace'], '', 5, ARRAY['تسويق','محتوى','Notion','Slack','اعتماد'], ARRAY['#marketing','#contentapproval','#n8n','#Notion','#Slack'], 'التسويق', 'Manual / Webhook', ARRAY['Notion','Slack','n8n'], false, '', ARRAY['content-repurpose-pipeline'], '{}', '{}', ARRAY['التأخير بسبب غياب المراجع','نقص بيانات النشر'], 'آمن', 'لا بيانات حساسة. تأكد من صلاحيات Notion المناسبة.', true, '[]'::jsonb, NULL, now()),
  ('pdf-certificates', 'automation', 'workflow', 'published', false, 60, 'إصدار شهادات PDF تلقائيًا', 'Education Automation', 'education', 'متوسط', 'إصدار الشهادات يدويًا يستهلك وقتًا ويزيد احتمال الأخطاء.', 'عند إكمال المسار يُولد PDF ويرسل للطالب ويحفظ في Drive.', ARRAY['Google Sheets','PDF Generator (Carbone / PDFMonkey)','Gmail','Google Drive'], ARRAY['إعداد قالب الشهادة في PDF Generator','ربط بيانات الطالب بالقالب','حفظ الشهادة في Google Drive','إرسال نسخة للطالب عبر Gmail'], ARRAY['الاسم','المسار','التاريخ','الدرجة'], 'شهادة PDF مرسلة ومحفوظة في Drive.', ARRAY['فحص الاسم بالعربية في PDF','التأكد من صحة التواريخ','اختبار المرفق في Gmail'], ARRAY['أسماء مكتوبة خطأ','فشل PDF Generator'], ARRAY['إضافة QR للتحقق','ربطها بسجل الشهادات'], '70 دقيقة', 'Service-ready', 'New row in sheet', ARRAY['Generate PDF','Save to Drive','Send email','Update record'], 'أصدر شهادات PDF مُخصَّصة تلقائيًا عند اكتمال الطالب أي دورة.', 'شهادات فورية دون تدخل يدوي — احترافية أعلى وسرعة أكبر.', ARRAY['Google Workspace','حساب PDF Generator'], 'أضف API Key لـ PDF Generator في n8n Credentials. لا تضعه في الـ node مباشرة.', 5, ARRAY['شهادات','PDF','تعليم','Google Drive','Gmail'], ARRAY['#certificates','#n8n','#automation','#تعليم','#PDF'], 'التعليم', 'Polling / Webhook', ARRAY['Google Sheets','Google Drive','Gmail','PDFMonkey'], false, '', ARRAY['student-welcome-flow','course-registration-pipeline'], '{}', '{}', ARRAY['أسماء مكتوبة بشكل خاطئ بسبب encoding','فشل إنشاء PDF عند بيانات ناقصة'], 'آمن', 'بيانات الطلاب عامة. لا تخزن بيانات دفع في الـ workflow.', true, '[]'::jsonb, NULL, now()),
  ('hr-candidate-screening', 'automation', 'workflow', 'published', false, 70, 'فرز المرشحين الأولي بالذكاء الاصطناعي', 'HR & Recruitment', 'hr', 'متوسط', 'التقديمات الكثيرة تُراجع يدويًا دون ترتيب واضح.', 'جمع الطلبات وتصنيفها وإرسال تحديثات أولية وإنشاء shortlist.', ARRAY['Google Forms','Google Sheets','AI Model'], ARRAY['تحديد معايير الفرز','بناء prompt التقييم','إضافة score أولي تلقائي','تحديث حالة المرشح في الـ sheet'], ARRAY['الاسم','السيرة الذاتية','الخبرة','الدور'], 'قائمة قصيرة + تحديثات status مبدئية.', ARRAY['فحص حالات الرفض والقبول','مراجعة الـ score مع مراجع بشري','اختبار تحديث السجلات'], ARRAY['تحيّز في التقييم الآلي','بيانات السيرة حساسة'], ARRAY['إضافة جدولة مقابلات','ربطها بتوقيع العقود'], '70 دقيقة', 'Pro', 'New form submission', ARRAY['Record application','AI score','Update status','Notify HR'], 'اجمع التقديمات وصنّفها بالذكاء الاصطناعي وأرسل تحديثات أولية تلقائيًا.', 'توفير 5+ ساعات أسبوعيًا — تركيز على المرشحين الجيدين فقط.', ARRAY['Google Workspace','Gemini أو OpenAI API'], 'استخدم AI API key في n8n Credentials. لا تعرض السيرة الذاتية لـ AI بدون موافقة المرشح.', 5, ARRAY['HR','تعيين','AI','فرز','موارد بشرية'], ARRAY['#HR','#recruitment','#n8n','#AI','#automation'], 'الموارد البشرية', 'Webhook / Form', ARRAY['Google Forms','Google Sheets','Gemini API'], false, '', ARRAY['hr-onboarding-pack','attendance-alerts'], '{}', '{}', ARRAY['اعتماد زائد على score آلي دون مراجعة بشرية','نقص بيانات المرشح'], 'يحتاج مراجعة', 'السيرة الذاتية بيانات شخصية حساسة. لا ترسل للـ AI بدون سياسة خصوصية واضحة. المراجعة البشرية ضرورية دائمًا.', true, '[]'::jsonb, NULL, now()),
  ('customer-request-routing', 'automation', 'workflow', 'published', false, 80, 'توجيه طلبات العملاء للفريق الصحيح', 'Customer Support', 'support', 'متوسط', 'الطلبات تدخل من أكثر من قناة ولا تصل للشخص الصحيح بسرعة.', 'تحويل الطلب إلى ticket وتوجيهه حسب النوع والأولوية.', ARRAY['Webhook / Form','Slack','Notion أو Jira'], ARRAY['تصنيف أنواع الطلبات (تقني / مالي / عام)','تحديد فرق الاستلام لكل نوع','إضافة تنبيه SLA للطلبات الحرجة','ربط Webhook مصدر الطلب'], ARRAY['اسم العميل','نوع الطلب','الأولوية','الوصف'], 'ticket موجه وإشعار لفريق التنفيذ.', ARRAY['اختبر كل فئة طلبات','فحص SLA tags','اختبار سيناريو escalation'], ARRAY['تصنيف خاطئ يؤخر الحل'], ARRAY['إضافة AI triage','إضافة رضا العميل post-resolution'], '55 دقيقة', 'Pro', 'Webhook', ARRAY['Classify request','Create ticket','Notify team','Set SLA'], 'وجّه كل طلب دعم تلقائيًا للفريق المناسب حسب النوع والأولوية.', 'وقت استجابة أسرع + تجربة عميل أفضل + SLA واضح.', ARRAY['Slack Workspace','Notion أو أداة Ticketing'], '', 4, ARRAY['دعم','tickets','Slack','توجيه','SLA'], ARRAY['#customersupport','#n8n','#automation','#Slack','#ticketing'], 'خدمة العملاء', 'Webhook', ARRAY['Slack','Notion','Webhook'], false, '', ARRAY['support-ticket-escalation','support-feedback-loop'], '{}', '{}', ARRAY['تصنيف غير صحيح','فقدان بيانات من القناة'], 'آمن', 'لا بيانات مالية أو كلمات مرور في هذا الـ workflow.', true, '[]'::jsonb, NULL, now()),
  ('invoice-archive-bot', 'automation', 'workflow', 'published', false, 90, 'أرشفة الفواتير تلقائيًا من البريد', 'File Automation', 'finance', 'متوسط', 'الفواتير تتراكم في البريد دون أرشفة مرجعية واضحة.', 'التقاط المرفق، حفظه في Drive، وتسجيل بياناته المرجعية.', ARRAY['Gmail','Google Drive','Google Sheets'], ARRAY['تحديد الرسائل المصدر (مثلًا: subject يحتوي فاتورة)','استخراج الحقول الأساسية','حفظ المرفق في مجلد Drive محدد','تسجيل البيانات في Google Sheets'], ARRAY['اسم المورد','رقم الفاتورة','المبلغ','التاريخ'], 'ملف مؤرشف + سجل مرجعي يمكن البحث فيه.', ARRAY['فحص اسم الملف المحفوظ','التأكد من duplicate handling','تأكيد التخزين في المجلد الصحيح'], ARRAY['مرفقات غير متوقعة','فواتير مكررة'], ARRAY['إضافة OCR لاستخراج الأرقام','ربطها بموافقة مالية'], '50 دقيقة', 'Pro', 'New email', ARRAY['Extract attachment','Save to Drive','Log to Sheets'], 'التقط فواتير البريد الإلكتروني تلقائيًا وأرشفها في Drive مع سجل مرجعي.', 'لا فاتورة مفقودة + بحث فوري + محاسبة أسهل.', ARRAY['Google Workspace'], '', 4, ARRAY['فواتير','أرشفة','Gmail','Google Drive','محاسبة'], ARRAY['#invoices','#n8n','#automation','#GoogleDrive','#Gmail'], 'المالية والمحاسبة', 'Polling / Webhook', ARRAY['Gmail','Google Drive','Google Sheets'], false, '', ARRAY['drive-upload-notify','weekly-sales-report'], '{}', '{}', ARRAY['مرفقات ناقصة أو بصيغة غير مدعومة','فواتير متكررة بدون deduplication'], 'آمن', 'لا تشارك بيانات الفواتير مع خدمات خارجية. استخدم Google Drive الخاص بمؤسستك.', true, '[]'::jsonb, NULL, now()),
  ('website-lead-to-whatsapp', 'automation', 'workflow', 'published', false, 100, 'استفسار الموقع → واتساب + CRM في ثوانٍ', 'E-commerce Automation', 'sales', 'مبتدئ', 'الاستفسارات من الموقع لا يتبعها تواصل سريع.', 'استقبال الاستفسار ثم إشعار البائع وإرسال رسالة أولية للعميل.', ARRAY['Website Form / Webhook','CRM','WhatsApp Business API'], ARRAY['ربط نموذج الموقع بـ Webhook','إعداد lead owner في CRM','إضافة رسالة أولية لـ WhatsApp','اختبار على رقم sandbox أولًا'], ARRAY['الاسم','رقم الهاتف','الخدمة'], 'lead محدث + رسالة أولية + task متابعة.', ARRAY['اختبر إرسال النموذج','فحص Webhook trigger','تأكد من تعيين owner في CRM'], ARRAY['رقم هاتف خاطئ','رسالة واتساب مزدوجة'], ARRAY['إضافة lead scoring','ربط بجدولة مكالمة'], '35 دقيقة', 'Service-ready', 'New form submission', ARRAY['Update CRM','Send WhatsApp','Notify sales'], 'أرسل رسالة واتساب فورية للعميل فور إرساله استفسار من موقعك وسجّله في CRM.', 'استجابة في دقيقة — 3x تحسين في معدل الرد.', ARRAY['WhatsApp Business API','CRM'], 'استخدم Twilio WhatsApp Sandbox للاختبار قبل الإنتاج.', 4, ARRAY['موقع','واتساب','leads','CRM','تجارة إلكترونية'], ARRAY['#ecommerce','#WhatsApp','#n8n','#automation','#leads'], 'التجارة الإلكترونية', 'Webhook / Form', ARRAY['Webhook','WhatsApp Business API','CRM'], false, '', ARRAY['lead-followup-whatsapp','google-form-to-crm'], '{}', '{}', ARRAY['رقم هاتف غير صالح','lead بلا owner'], 'يحتاج مراجعة', 'WhatsApp Business API يتطلب موافقة Meta. اختبر في Sandbox أولًا.', true, '[]'::jsonb, NULL, now()),
  ('course-registration-pipeline', 'automation', 'workflow', 'published', false, 110, 'خط تسجيل الدورات الكامل', 'Education Automation', 'education', 'متوسط', 'تسجيل الطلاب ومتابعة المدفوعات والتأكيدات تتم يدويًا.', 'رحلة من التسجيل إلى التأكيد والدفع والرسالة النهائية.', ARRAY['Google Forms','Google Sheets','Gmail','Calendar'], ARRAY['تصميم حقول النموذج','إضافة حالة الدفع للـ sheet','إعداد رسائل التأكيد والتذكير','إشعار فريق المتابعة'], ARRAY['اسم الطالب','اسم الدورة','وسيلة الدفع','موعد البداية'], 'سجل طالب + تذكير + تأكيد القبول.', ARRAY['فحص status changes','اختبار رسائل ما قبل البداية','مراجعة duplicate prevention'], ARRAY['تسجيل مكرر','حالة دفع خاطئة'], ARRAY['ربطها بنظام الشهادات','إضافة reminder لكل جلسة'], '65 دقيقة', 'Service-ready', 'New form submission', ARRAY['Record student','Send confirmation','Schedule reminder','Notify team'], 'رحلة متكاملة من التسجيل إلى التأكيد والتذكير — كلها تلقائية.', 'صفر أخطاء تسجيل + تجربة طالب احترافية.', ARRAY['Google Workspace'], '', 5, ARRAY['تسجيل','دورات','تعليم','Google Forms','Calendar'], ARRAY['#education','#n8n','#automation','#تعليم','#registration'], 'التعليم', 'Webhook / Form', ARRAY['Google Forms','Gmail','Google Calendar'], false, '', ARRAY['student-welcome-flow','pdf-certificates'], '{}', '{}', ARRAY['تسجيلات مكررة','حالة دفع غير محدثة'], 'آمن', 'لا تخزن بيانات بطاقات دفع في النماذج أو الـ sheets.', true, '[]'::jsonb, NULL, now()),
  ('attendance-alerts', 'automation', 'workflow', 'published', false, 120, 'تنبيهات الحضور والانصراف الفورية', 'HR & Recruitment', 'hr', 'مبتدئ', 'إدارة الحضور اليدوية تؤخر معرفة الغياب أو التأخير.', 'يُسجل حضور الموظف أو الطالب ثم تُرسل تنبيهات للحالات الاستثنائية.', ARRAY['Google Forms','Google Sheets','Telegram أو Slack'], ARRAY['إنشاء نموذج check-in','إعداد شروط التأخير (مثلًا: بعد 9:00 صباحًا)','ربط التنبيهات بـ Telegram أو Slack','اختبار على سيناريو تأخير وهمي'], ARRAY['الاسم','الوقت','الفرع','الحالة'], 'سجل حضور + تنبيه تأخير أو غياب.', ARRAY['اختبر سيناريو تأخير','فحص المنطقة الزمنية','منع check-in مزدوج'], ARRAY['بيانات وقت غير دقيقة'], ARRAY['إضافة dashboard يومية','موافقة أسباب الغياب'], '40 دقيقة', 'Free', 'New form submission', ARRAY['Record attendance','Check rules','Send alert','Update log'], 'سجّل الحضور تلقائيًا وأرسل تنبيهات فورية لحالات التأخير والغياب.', 'تتبع فوري — إدارة HR بدون جداول يدوية يومية.', ARRAY['Google Workspace','Telegram Bot أو Slack Workspace'], '', 4, ARRAY['حضور','HR','Telegram','Google Forms','موارد بشرية'], ARRAY['#attendance','#HR','#n8n','#automation','#Telegram'], 'الموارد البشرية', 'Webhook / Form', ARRAY['Google Forms','Google Sheets','Telegram'], false, '', ARRAY['hr-onboarding-pack','hr-candidate-screening'], '{}', '{}', ARRAY['سوء إدخال الوقت','check-in مزدوج لنفس الشخص'], 'آمن', 'بيانات الحضور داخلية. لا تشارك مع جهات خارجية.', true, '[]'::jsonb, NULL, now()),
  ('hr-onboarding-pack', 'automation', 'workflow', 'published', false, 130, 'حزمة Onboarding للموظف الجديد', 'HR & Recruitment', 'hr', 'متوسط', 'الموظف الجديد يستقبل الخطوات والوثائق بشكل متفرق.', 'بعد اعتماد التوظيف تُنشأ قائمة مهام ورسائل وبنية مستندات.', ARRAY['Trello أو Notion','Gmail','Google Drive'], ARRAY['إنشاء قوالب مهام Onboarding','إعداد مجلد الموظف في Drive','إرسال رسالة الترحيب الافتتاحية','إشعار المدير بتاريخ البداية'], ARRAY['اسم الموظف','الدور','تاريخ البداية','المدير'], 'مهام onboarding + مجلد + رسالة ترحيب.', ARRAY['اختبر تاريخ البداية','فحص المجلد المُنشأ','مراجعة قائمة المهام'], ARRAY['بيانات موظف ناقصة'], ARRAY['إضافة equipment checklist','ربطها بالتدريب الأولي'], '50 دقيقة', 'Service-ready', 'New employee approved', ARRAY['Create task list','Set up folder','Send welcome email','Notify manager'], 'استقبل كل موظف جديد بحزمة onboarding كاملة — مهام ومستندات ورسالة ترحيب.', 'تجربة onboarding احترافية + موظف جاهز أسرع.', ARRAY['Google Workspace','Trello أو Notion'], '', 5, ARRAY['onboarding','HR','موظف جديد','Trello','Google Drive'], ARRAY['#onboarding','#HR','#n8n','#automation','#موارد_بشرية'], 'الموارد البشرية', 'Webhook / Manual', ARRAY['Trello','Gmail','Google Drive'], false, '', ARRAY['attendance-alerts','hr-candidate-screening'], '{}', '{}', ARRAY['معلومات موظف ناقصة','تأخر manager handoff'], 'آمن', 'بيانات الموظف داخلية. لا تشارك مع جهات خارجية.', true, '[]'::jsonb, NULL, now()),
  ('abandoned-cart-reminder', 'automation', 'workflow', 'published', false, 140, 'استعادة السلة المتروكة — بريد + متابعة', 'E-commerce Automation', 'marketing', 'متوسط', 'العملاء يتركون السلة دون متابعة منظمة.', 'بعد ترك السلة يُرسل تذكير وربما incentive مناسب.', ARRAY['Email Platform','CRM','E-commerce Webhook'], ARRAY['تحديد شرط السلة المتروكة (انتظر 30 دقيقة)','إعداد محتوى رسالة التذكير','إضافة شرط الإيقاف عند إتمام الشراء','تتبع نتائج الاستعادة'], ARRAY['اسم العميل','عناصر السلة','القيمة'], 'رسالة recovery ومتابعة conversion.', ARRAY['اختبر الوقت بعد ترك السلة','فحص إلغاء الرسالة عند إتمام الشراء','تتبع conversion rate'], ARRAY['إزعاج العميل بكثرة الرسائل'], ARRAY['إضافة WhatsApp fallback','تقارير conversion تفصيلية'], '50 دقيقة', 'Pro', 'Cart abandoned event', ARRAY['Wait delay','Send reminder email','Track response','Stop if purchased'], 'تعافَ من السلات المتروكة بتسلسل رسائل ذكي يُذكّر العميل ويُقنعه بالعودة.', '10–15% استعادة مبيعات مفقودة من السلات المتروكة.', ARRAY['حساب Email Platform (Brevo / Mailchimp)','E-commerce Platform'], 'أضف API Key لـ Email Platform في n8n Credentials.', 4, ARRAY['سلة متروكة','تجارة إلكترونية','email','استعادة','CRM'], ARRAY['#ecommerce','#abandonedcart','#n8n','#automation','#email'], 'التجارة الإلكترونية', 'Webhook', ARRAY['Email Platform','CRM','E-commerce Webhook'], false, '', ARRAY['website-lead-to-whatsapp','crm-renewal-reminder'], '{}', '{}', ARRAY['إرسال رسائل مزعجة أكثر من مرة','عدم إيقاف التسلسل بعد الشراء'], 'يحتاج مراجعة', 'تحقق من قوانين GDPR/PDPA الخاصة ببلدك قبل إرسال رسائل تسويقية.', true, '[]'::jsonb, NULL, now()),
  ('drive-upload-notify', 'automation', 'workflow', 'published', false, 150, 'رفع ملف إلى Drive مع إشعار تلقائي', 'Internal Operations', 'operations', 'مبتدئ', 'الملفات تصل لكن لا توجد متابعة واضحة لمن رفعها أو أين خُزنت.', 'أي upload يتم حفظه داخل المجلد الصحيح مع سجل وإشعار.', ARRAY['Google Drive','Google Sheets','Slack أو Email'], ARRAY['تحديد المجلدات المستهدفة','حفظ metadata الملف في Sheets','إرسال إشعار لـ Slack أو Email'], ARRAY['اسم الملف','رافع الملف','التاريخ','الفئة'], 'ملف منظم + إشعار + سجل مرجعي.', ARRAY['اختبر رفع ملف تجريبي','فحص المجلد الصحيح','اختبار duplicate handling'], ARRAY['مجلد خاطئ'], ARRAY['إضافة approval قبل النقل','naming convention آلي'], '25 دقيقة', 'Free', 'File upload', ARRAY['Move to folder','Log metadata','Send notification'], 'نظّم كل ملف يُرفع إلى Drive تلقائيًا وأشعر الفريق فورًا.', 'فريق منظم + صفر ملفات ضائعة + بحث فوري.', ARRAY['Google Workspace','Slack Workspace'], '', 3, ARRAY['Google Drive','ملفات','تنظيم','Slack','إشعارات'], ARRAY['#GoogleDrive','#n8n','#automation','#files','#operations'], 'العمليات الداخلية', 'Webhook / Polling', ARRAY['Google Drive','Google Sheets','Slack'], false, '', ARRAY['invoice-archive-bot','meeting-summary-distribution'], '{}', '{}', ARRAY['مجلد غير صحيح بسبب naming','ملفات ناقصة metadata'], 'آمن', 'لا بيانات حساسة. تأكد من صلاحيات Drive مناسبة للفريق.', true, '[]'::jsonb, NULL, now()),
  ('meeting-summary-distribution', 'automation', 'workflow', 'published', false, 160, 'توزيع ملخص الاجتماع بالذكاء الاصطناعي', 'AI Agents', 'operations', 'متوسط', 'نقاط الاجتماع تضيع إذا لم تُحول إلى tasks ورسالة متابعة.', 'تلخيص الاجتماع ثم توزيع القرار والمهام على الأطراف تلقائيًا.', ARRAY['AI Model (Gemini / OpenAI)','Notion','Gmail أو Slack'], ARRAY['أدخل ملاحظات الاجتماع كـ input','أضف AI node مع prompt استخراج المهام','أنشئ tasks في Notion','أرسل ملخصًا لكل الحضور'], ARRAY['المحاور','الحضور','المهام','المواعيد'], 'ملخص اجتماع مع action items ومسؤوليات.', ARRAY['فحص دقة الملخص','التأكد من التوزيع الصحيح','اختبار التنسيق'], ARRAY['تلخيص غير مكتمل'], ARRAY['ربطها بتقويم لمتابعة المهام','تحديث project board تلقائيًا'], '45 دقيقة', 'Pro', 'Manual button', ARRAY['Input summary','AI extract tasks','Create Notion tasks','Send email to attendees'], 'لخّص الاجتماع بالذكاء الاصطناعي ووزّع المهام على الأطراف المعنية تلقائيًا.', 'صفر مهام منسية + مسؤوليات واضحة بعد كل اجتماع.', ARRAY['حساب AI API','Notion Workspace'], 'استخدم Gemini API key في n8n Credentials. لا تُرسل محتوى سري إلى AI خارجي.', 5, ARRAY['اجتماعات','AI','Notion','مهام','ذكاء اصطناعي'], ARRAY['#meetings','#AI','#n8n','#automation','#Notion'], 'العمليات الداخلية', 'Manual', ARRAY['Gemini API','Notion','Gmail'], false, '', ARRAY['daily-ai-email-brief','drive-upload-notify'], '{}', '{}', ARRAY['ملاحظات غير منظمة تعطي AI نتيجة ضعيفة','مهام بلا owner'], 'يحتاج مراجعة', 'لا ترسل محتوى سري (بيانات مالية / عقود) إلى AI خارجي.', true, '[]'::jsonb, NULL, now()),
  ('crm-renewal-reminder', 'automation', 'workflow', 'published', false, 170, 'تذكير تجديد العملاء قبل الموعد', 'CRM & Sales', 'sales', 'مبتدئ', 'الاشتراكات تقترب من الانتهاء دون متابعة مبكرة.', 'فحص تواريخ الانتهاء وإرسال تنبيه داخلي ورسالة تواصل.', ARRAY['CRM','Email','Google Calendar'], ARRAY['تحديد نافذة التنبيه (30 يوم قبل)','إعداد رسالة التجديد','إنشاء مهمة للمدير المسؤول'], ARRAY['اسم العميل','تاريخ الانتهاء','صاحب الحساب'], 'تذكير للتجديد قبل الموعد مع owner واضح.', ARRAY['اختبر عميل قريب الانتهاء','فحص timezone','إلغاء المهمة عند التجديد'], ARRAY['تنبيهات مكررة'], ARRAY['إضافة scoring للعقود المهمة','ربطها بعروض التجديد'], '25 دقيقة', 'Free', 'Scheduled time', ARRAY['Check renewal dates','Filter near-expiry','Send reminder','Create follow-up task'], 'تذكّر فريق المبيعات بكل عقد أو اشتراك يقترب من الانتهاء قبل 30 يومًا.', 'زيادة renewal rate + إيرادات محافظة على العملاء.', ARRAY['CRM','Gmail'], '', 4, ARRAY['تجديد','CRM','عملاء','عقود','مبيعات'], ARRAY['#CRM','#renewal','#n8n','#automation','#مبيعات'], 'المبيعات', 'Schedule', ARRAY['CRM','Gmail','Google Calendar'], false, '', ARRAY['google-form-to-crm','lead-followup-whatsapp'], '{}', '{}', ARRAY['تواريخ غير محدثة في CRM','تنبيه متكرر مزعج'], 'آمن', 'بيانات العقود داخلية. لا تشارك مع جهات خارجية.', true, '[]'::jsonb, NULL, now()),
  ('appointment-confirmation', 'automation', 'workflow', 'published', false, 180, 'تأكيد المواعيد والتذكير التلقائي', 'Freelance Client Workflows', 'operations', 'مبتدئ', 'الحجوزات تحتاج تأكيدًا وتذكيرًا لتقليل الغياب.', 'عند إنشاء الموعد يخرج تأكيد ثم reminder قبل الموعد.', ARRAY['Google Calendar','Gmail','WhatsApp concepts'], ARRAY['تحديد قنوات الإرسال (Email / WhatsApp)','إعداد reminder offset (مثلًا: قبل 24 ساعة)','حفظ status التأكيد'], ARRAY['اسم العميل','الوقت','الخدمة','القناة'], 'تأكيد + reminder + تحديث حالة الحضور المتوقعة.', ARRAY['اختبر timezone','اختبر الموعد القريب جدًا','فحص سيناريو إلغاء الموعد'], ARRAY['إرسال reminder بعد الموعد'], ARRAY['إضافة reschedule link','تتبع no-show rate'], '35 دقيقة', 'Service-ready', 'Schedule event', ARRAY['Send confirmation','Schedule reminder','Update status'], 'قلّل الغياب عن المواعيد بتأكيد تلقائي + reminder قبل الموعد.', 'تقليل الغياب 30–50% + تجربة عميل أفضل.', ARRAY['Google Workspace'], '', 3, ARRAY['مواعيد','تذكير','Calendar','فريلانس','خدمات'], ARRAY['#appointments','#n8n','#automation','#Calendar','#reminders'], 'الفريلانس والخدمات', 'Polling / Calendar', ARRAY['Google Calendar','Gmail','WhatsApp'], false, '', ARRAY['course-registration-pipeline','crm-renewal-reminder'], '{}', '{}', ARRAY['إرسال بتوقيت خاطئ','reminder مكرر'], 'آمن', 'لا بيانات حساسة. تأكد من صحة المنطقة الزمنية.', true, '[]'::jsonb, NULL, now()),
  ('content-repurpose-pipeline', 'automation', 'workflow', 'published', false, 190, 'إعادة توظيف المحتوى عبر القنوات', 'Marketing Campaign Automation', 'marketing', 'متوسط', 'المحتوى يُنتج مرة واحدة ولا يُعاد توزيعه بذكاء.', 'من فكرة واحدة يخرج نصوص مختصرة ونسخة بريد ونسخة منشور.', ARRAY['Notion','AI Model (Gemini / OpenAI)','Google Sheets'], ARRAY['أدخل الفكرة الأصلية كـ input','أضف AI node مع prompt لكل قناة','احفظ النسخ في Notion','أرسل للمراجعة'], ARRAY['العنوان','الجمهور','القناة','الهدف'], 'نسخ متعددة جاهزة للمراجعة (Twitter / LinkedIn / Email / Blog).', ARRAY['اختبر طول النص لكل قناة','فحص نبرة الرسائل','تأكد من عدم التكرار الزائد'], ARRAY['محتوى متشابه جدًا بين القنوات'], ARRAY['إضافة approval قبل الحفظ','ربطها بجدولة نشر تلقائية'], '55 دقيقة', 'Pro', 'Manual button', ARRAY['Get content idea','AI generate variants','Format per channel','Save drafts'], 'من فكرة واحدة إلى محتوى لكل قناة — تلقائيًا ومنسّق جاهز للنشر.', '3x إنتاجية محتوى بنفس الجهد.', ARRAY['Notion Workspace','AI API'], 'استخدم Gemini API key في n8n Credentials.', 5, ARRAY['محتوى','تسويق','AI','Notion','إعادة توظيف'], ARRAY['#contentmarketing','#AI','#n8n','#automation','#تسويق'], 'التسويق', 'Manual', ARRAY['Notion','Gemini API','Google Sheets'], false, '', ARRAY['social-content-approval','daily-ai-email-brief'], '{}', '{}', ARRAY['prompt عام ينتج نصًا متشابهًا للكل','نسيان تخصيص النبرة لكل قناة'], 'متقدم', 'راجع كل النسخ قبل النشر. AI يمكن أن ينتج محتوى غير مناسب إذا كان الـ prompt غير دقيق.', true, '[]'::jsonb, NULL, now()),
  ('expense-report-approval', 'automation', 'workflow', 'published', false, 200, 'اعتماد تقارير المصروفات تلقائيًا', 'Finance Automation', 'finance', 'متوسط', 'تأخر اعتماد المصروفات وفقدان المرفقات في سلاسل البريد الإلكتروني.', 'استلام طلب مصروف → التحقق من الحد المالي → إرسال للمعتمد → تحديث السجل عند القرار.', ARRAY['Google Forms','Gmail','Google Sheets'], ARRAY['إنشاء نموذج الطلب بالحقول المطلوبة','ربط النموذج بجدول المصروفات','إعداد منطق الاعتماد (حد مالي)','إرسال بريد للمعتمد مع رابط الموافقة','تحديث السجل عند القرار'], ARRAY['اسم الموظف','المبلغ','السبب','المرفق'], 'طلب محفوظ + بريد اعتماد + تحديث الحالة في الجدول.', ARRAY['اختبر طلب أقل من الحد المالي','اختبر طلب يتجاوز الحد','تحقق من تحديث الحالة في الجدول'], ARRAY['موافقة تلقائية بدون مراجعة للمبالغ الكبيرة'], ARRAY['إضافة تذكير تلقائي عند تأخر الرد','ربط بنظام محاسبة'], '60 دقيقة', 'Free', 'Form submission', ARRAY['Send email','Update row','Conditional branch'], 'يستقبل طلبات المصروفات، يُرسلها للاعتماد، ويُحدّث السجلات فور الموافقة.', 'تقليل دورة الاعتماد من أيام إلى ساعات وضمان توثيق كامل.', ARRAY['Google Workspace'], '', 5, ARRAY['مالية','اعتماد','مصروفات','موافقة','Google Sheets'], ARRAY['#finance','#automation','#n8n','#مالية','#workflow'], 'المالية', 'Webhook / Form', ARRAY['Google Forms','Gmail','Google Sheets'], true, '', ARRAY['invoice-archive-bot','weekly-sales-report'], '{}', '{}', ARRAY['غياب منطق التفريع حسب المبلغ','عدم إرفاق الفاتورة'], 'يحتاج مراجعة', 'تأكد من وجود حد مالي وموافقة يدوية للمبالغ الكبيرة.', true, '[]'::jsonb, NULL, now()),
  ('customer-feedback-routing', 'automation', 'workflow', 'published', false, 210, 'توجيه تقييمات العملاء للفريق المختص', 'Customer Support', 'support', 'مبتدئ', 'تقييمات العملاء السلبية تضيع دون متابعة أو تصل متأخرة للمسؤول.', 'استلام تقييم → تصنيف حسب النقاط → توجيه للمسؤول المختص → تسجيل في الجدول.', ARRAY['Google Forms','Gmail','Google Sheets'], ARRAY['إنشاء نموذج التقييم','إضافة منطق التفريع: 1-2 نجوم → دعم عاجل، 4-5 → شكر','إعداد قوالب البريد لكل حالة','ربط بجدول رصد الرضا'], ARRAY['اسم العميل','التقييم (1-5)','التعليق','نوع الطلب'], 'توجيه الشكاوى فورًا + تسجيل كل التقييمات.', ARRAY['اختبر تقييمًا سلبيًا (1 نجمة)','اختبر تقييمًا إيجابيًا (5 نجوم)','تحقق من التسجيل في الجدول'], ARRAY['إرسال ردود آلية غير مناسبة لحالات حساسة'], ARRAY['إضافة AI لتلخيص الشكوى','ربط بـ CRM لتحديث سجل العميل'], '40 دقيقة', 'Free', 'New form response', ARRAY['Send email','Add row','Conditional branch'], 'يجمع تقييمات العملاء ويُوجّهها تلقائيًا للفريق المناسب حسب النوع والتقييم.', 'رد أسرع على الشكاوى وتحسين رضا العملاء بشكل قابل للقياس.', ARRAY['Google Workspace'], '', 4, ARRAY['تقييمات','دعم','عملاء','شكاوى','Google Forms'], ARRAY['#customerservice','#automation','#n8n','#دعم_عملاء'], 'خدمة العملاء', 'Webhook / Form', ARRAY['Google Forms','Gmail','Google Sheets'], true, '', ARRAY['customer-request-routing','appointment-confirmation'], '{}', '{}', ARRAY['غياب التفريع حسب نوع الشكوى','نسيان إشعار المدير عند الحالات الحرجة'], 'آمن', 'تأكد من مراجعة بشرية للشكاوى الحرجة قبل الرد.', true, '[]'::jsonb, NULL, now()),
  ('newsletter-subscriber-welcome', 'automation', 'workflow', 'published', false, 220, 'استقبال المشتركين الجدد في النشرة البريدية', 'Marketing Campaign', 'marketing', 'مبتدئ', 'المشتركون الجدد لا يحصلون على ترحيب فوري، مما يُضعف الانطباع الأول.', 'تسجيل جديد → إرسال رسالة ترحيب → إضافة للشريحة المناسبة → جدولة رسالة المتابعة.', ARRAY['Google Forms','Gmail','Google Sheets'], ARRAY['إعداد نموذج الاشتراك','كتابة قالب رسالة الترحيب','إضافة منطق التصنيف حسب الاهتمام','جدولة رسالة متابعة بعد 3 أيام'], ARRAY['اسم المشترك','البريد الإلكتروني','الاهتمام'], 'رسالة ترحيب فورية + تصنيف في الشريحة الصحيحة.', ARRAY['اختبر اشتراكًا جديدًا','تأكد من وصول رسالة الترحيب','تحقق من التصنيف في الشريحة'], ARRAY['وضع البريد في مجلد Spam عند الإرسال الجماعي'], ARRAY['إضافة سلسلة onboarding أطول','ربط بـ CRM لتتبع النشاط'], '35 دقيقة', 'Free', 'New subscriber', ARRAY['Send email','Add to segment','Schedule follow-up'], 'يُرسل سلسلة ترحيب تلقائية لكل مشترك جديد في النشرة ويُنظّم قائمتك.', 'رفع معدل فتح الرسائل الأولى وبناء علاقة قوية من أول لحظة.', ARRAY['Google Workspace'], '', 3, ARRAY['نشرة بريدية','تسويق','مشتركون','ترحيب','Gmail'], ARRAY['#emailmarketing','#automation','#newsletter','#تسويق'], 'التسويق', 'Webhook / Form', ARRAY['Gmail','Google Sheets'], true, '', ARRAY['social-content-approval','content-repurpose-pipeline'], '{}', '{}', ARRAY['غياب إلغاء الاشتراك في الرسالة','إرسال رسائل متكررة لنفس البريد'], 'آمن', 'أضف رابط إلغاء الاشتراك في كل رسالة.', true, '[]'::jsonb, NULL, now()),
  ('project-task-from-email', 'automation', 'workflow', 'published', false, 230, 'تحويل الطلبات الواردة بالبريد إلى مهام تلقائيًا', 'Internal Operations', 'operations', 'متوسط', 'الطلبات الواردة بالبريد تضيع في صندوق الوارد دون متابعة أو إسناد.', 'بريد جديد → استخراج البيانات → إنشاء مهمة في Notion → إشعار المسؤول.', ARRAY['Gmail','Notion','n8n'], ARRAY['إعداد فلتر Gmail لبريد الطلبات','استخراج البيانات الأساسية (الموضوع، المُرسِل)','إنشاء قاعدة Notion','إعداد منطق الإسناد حسب الفئة'], ARRAY['موضوع البريد','المُرسِل','محتوى الطلب'], 'مهمة منظّمة مع عنوان وأولوية ومسؤول في Notion.', ARRAY['أرسل بريدًا تجريبيًا بصيغة محددة','تأكد من إنشاء المهمة تلقائيًا','تحقق من صحة الإسناد'], ARRAY['قراءة بريد خاص غير مقصود'], ARRAY['إضافة AI لتصنيف أولوية المهمة','ربط بـ Slack لإشعار الفريق'], '55 دقيقة', 'Free', 'New email in Gmail', ARRAY['Extract data','Create task','Send notification'], 'يقرأ الطلبات الواردة في بريدك، يُنشئ مهمة منظّمة، ويُسند المسؤول تلقائيًا.', 'صفر مهام ضائعة وتوثيق كامل لكل طلب مع معيار استجابة واضح.', ARRAY['Gmail','Notion (مجاني)'], '', 4, ARRAY['Gmail','Notion','مهام','بريد','عمليات'], ARRAY['#productivity','#automation','#n8n','#Gmail','#Notion'], 'العمليات الداخلية', 'Polling / Email', ARRAY['Gmail','Notion','n8n'], true, '', ARRAY['drive-upload-notify','meeting-summary-distribution'], '{}', '{}', ARRAY['قراءة كل الرسائل بدون فلتر مناسب','غياب معالجة الأخطاء عند فشل الاستخراج'], 'يحتاج مراجعة', 'استخدم فلترًا محددًا (label أو مرسِل معروف) لتجنب قراءة رسائل خاصة.', true, '[]'::jsonb, NULL, now()),
  ('inventory-low-stock-alert', 'automation', 'workflow', 'published', false, 240, 'تنبيه نفاد المخزون وإعادة الطلب تلقائيًا', 'E-commerce Automation', 'operations', 'متوسط', 'اكتشاف نفاد المخزون متأخرًا يؤدي إلى فقدان مبيعات وخيبة أمل العملاء.', 'فحص الجدول بشكل دوري → اكتشاف المنتجات دون الحد → إرسال تنبيه → تسجيل الحادثة.', ARRAY['Google Sheets','Gmail','n8n'], ARRAY['إعداد جدول المخزون بعمود الحد الأدنى','إعداد trigger يومي في n8n','قراءة الجدول وفلترة المنتجات الناقصة','إرسال بريد تقرير يومي للمسؤول'], ARRAY['اسم المنتج','الكمية الحالية','حد التنبيه'], 'بريد تنبيه يومي يُدرج المنتجات الناقصة مع الكمية الحالية.', ARRAY['أضف منتجًا دون الحد وشغّل الـ workflow يدويًا','تأكد من وصول البريد مع قائمة المنتجات','تحقق من سجل التنبيهات'], ARRAY['تنبيهات كثيرة تُتجاهل إذا كان الحد غير دقيق'], ARRAY['إرسال طلب إعادة شراء تلقائيًا لمورّد محدد','إضافة تقرير أسبوعي'], '40 دقيقة', 'Free', 'Scheduled (daily)', ARRAY['Read sheet','Filter','Send email','Add log row'], 'يراقب مستويات المخزون ويُرسل تنبيهًا فوريًا عند الاقتراب من الحد الأدنى.', 'تجنب فقدان المبيعات وتقليل تكلفة الطوارئ في إعادة التخزين.', ARRAY['Google Workspace'], '', 4, ARRAY['مخزون','تجارة','تنبيه','Google Sheets','n8n'], ARRAY['#ecommerce','#inventory','#automation','#n8n','#تجارة'], 'التجارة الإلكترونية', 'Scheduled', ARRAY['Google Sheets','Gmail','n8n'], true, '', ARRAY['abandoned-cart-reminder','website-lead-to-whatsapp'], '{}', '{}', ARRAY['عدم تحديث جدول المخزون بانتظام','ضبط حد التنبيه منخفضًا جدًا'], 'آمن', 'بيانات داخلية فقط. لا مخاطر أمنية.', true, '[]'::jsonb, NULL, now()),
  ('social-media-post-scheduler', 'automation', 'workflow', 'published', false, 250, 'جدولة منشورات وسائل التواصل الاجتماعي', 'Marketing Campaign Automation', 'marketing', 'متوسط', 'فريق التسويق يضيع وقتًا في جدولة المنشورات يدويًا عبر قنوات متعددة.', 'قراءة المنشورات المجدولة من Airtable → التحقق من وقت النشر → نشر المحتوى على كل قناة.', ARRAY['Airtable','Buffer أو Later','Gmail'], ARRAY['إنشاء Airtable Base بأعمدة: المحتوى، القناة، وقت النشر، الحالة','ربط Buffer API أو Later لكل قناة','إعداد trigger كل ساعة للفحص','تحديث الحالة إلى ''منشور'' بعد النشر'], ARRAY['نص المنشور','الصورة','القناة','وقت النشر'], 'منشور محدد الوقت على كل قناة مع تحديث الحالة في Airtable.', ARRAY['أضف منشورًا مجدولًا لبعد 5 دقائق واختبر النشر','تحقق من تحديث الحالة في Airtable','فحص النشر على كل قناة منفردة'], ARRAY['نشر مكرر إذا لم يُحدَّث الـ status فورًا'], ARRAY['إضافة AI لاقتراح الوقت الأمثل للنشر','إحصائيات التفاعل تلقائيًا'], '50 دقيقة', 'Service-ready', 'Scheduled (every hour)', ARRAY['Read Airtable','Check schedule time','Post to channels','Update status'], 'جدوِل منشوراتك على عدة قنوات من مكان واحد وانشر تلقائيًا في الأوقات المثلى.', 'توفير 3–4 ساعات أسبوعيًا مع نشر منتظم وبدون تدخل يومي.', ARRAY['Airtable (مجاني)','حساب Buffer أو Later'], '', 4, ARRAY['منشورات','تسويق','جدولة','Airtable','وسائل تواصل'], ARRAY['#socialmedia','#automation','#n8n','#تسويق','#جدولة'], 'التسويق', 'Schedule', ARRAY['Airtable','Buffer','Gmail'], false, '', ARRAY['content-repurpose-pipeline','social-content-approval'], '{}', '{}', ARRAY['نسيان تحديد المنطقة الزمنية','بيانات اعتماد قناة غير مُحدَّثة'], 'يحتاج مراجعة', 'راجع المحتوى قبل الجدولة. لا تنشر محتوى لم يُعتمد.', true, '[]'::jsonb, NULL, now()),
  ('client-invoice-generator', 'automation', 'workflow', 'published', false, 260, 'توليد فاتورة العميل تلقائيًا عند إتمام الخدمة', 'Finance Automation', 'finance', 'مبتدئ', 'إنشاء الفواتير يدويًا بعد كل خدمة يستهلك الوقت ويُسبب أخطاء في الأرقام.', 'إدخال بيانات الخدمة في النموذج → توليد الفاتورة PDF → إرسالها للعميل → تسجيلها في جدول الإيرادات.', ARRAY['Google Forms','Google Sheets','Gmail'], ARRAY['إنشاء نموذج بيانات الخدمة','إعداد قالب الفاتورة في Sheets','ربط توليد PDF وإرساله بالبريد'], ARRAY['اسم العميل','الخدمة','المبلغ','تاريخ الاستحقاق'], 'فاتورة PDF ترسل للعميل + سجل في جدول الإيرادات.', ARRAY['أرسل نموذجًا تجريبيًا وتحقق من الفاتورة','تأكد من وصول البريد للعميل','فحص التسجيل في جدول الإيرادات'], ARRAY['إرسال فاتورة بمبلغ خاطئ'], ARRAY['إضافة رابط دفع إلكتروني في الفاتورة','تذكير تلقائي عند تأخر السداد'], '40 دقيقة', 'Free', 'Form submission', ARRAY['Generate invoice','Send email with PDF','Log to revenue sheet'], 'بعد إتمام كل خدمة تصدر فاتورة PDF احترافية وتُرسل للعميل فورًا.', 'توفير ساعة أسبوعيًا + فوترة فورية تُعجّل التحصيل.', ARRAY['Google Workspace'], '', 3, ARRAY['فاتورة','مالية','عملاء','PDF','فريلانس'], ARRAY['#invoice','#automation','#n8n','#فواتير','#freelance'], 'المالية والفريلانس', 'Webhook / Form', ARRAY['Google Forms','Gmail','Google Sheets'], false, '', ARRAY['expense-report-approval','invoice-archive-bot'], '{}', '{}', ARRAY['أرقام خاطئة بسبب تنسيق العملة','فاتورة بلا رقم تسلسلي'], 'يحتاج مراجعة', 'افحص الأرقام قبل الإرسال. أضف خطوة مراجعة للمبالغ الكبيرة.', true, '[]'::jsonb, NULL, now()),
  ('support-ticket-auto-assign', 'automation', 'workflow', 'published', false, 270, 'توزيع تذاكر الدعم تلقائيًا على الفريق', 'Customer Support', 'support', 'متوسط', 'التذاكر تتراكم في البريد وتُسنَد يدويًا مما يُبطئ الاستجابة.', 'استلام بريد الدعم → استخراج الفئة → إسناد للمختص → إنشاء تذكرة في Trello → إشعار العميل.', ARRAY['Gmail','Trello','Google Sheets'], ARRAY['إعداد صندوق بريد دعم مخصص','تعريف كلمات مفتاحية لكل فئة (تقني، فوترة، عام)','ربط Trello وإنشاء card لكل فئة','إرسال بريد تأكيد للعميل برقم التذكرة'], ARRAY['موضوع البريد','المُرسِل','فئة المشكلة'], 'تذكرة Trello مُسنَدة + بريد تأكيد للعميل + سجل في Sheets.', ARRAY['أرسل بريد دعم تقني وتحقق من الإسناد','اختبر فئة الفوترة وتأكد من تذكرة Trello','فحص بريد التأكيد للعميل'], ARRAY['تذكرة حرجة تذهب للمختص الخاطئ'], ARRAY['إضافة AI لتحديد الأولوية','SLA tracker تلقائي'], '55 دقيقة', 'Free', 'New email in support inbox', ARRAY['Extract category','Assign to agent','Create Trello card','Send acknowledgment'], 'كل طلب دعم يصل يُصنَّف ويُسنَد للشخص المناسب خلال ثوانٍ بدون تدخل يدوي.', 'تقليل وقت الاستجابة الأولي + توزيع عادل لعبء العمل.', ARRAY['Gmail','Trello (مجاني)'], '', 4, ARRAY['دعم','تذاكر','Trello','Gmail','خدمة عملاء'], ARRAY['#helpdesk','#automation','#n8n','#customerservice','#دعم'], 'خدمة العملاء', 'Polling / Email', ARRAY['Gmail','Trello','Google Sheets'], false, '', ARRAY['customer-feedback-routing','customer-request-routing'], '{}', '{}', ARRAY['أعضاء الفريق غير مضافين في Trello','فئات متداخلة تُسبب إسنادًا خاطئًا'], 'يحتاج مراجعة', 'أضف آلية escalation للتذاكر غير المستجاب لها خلال ساعة.', true, '[]'::jsonb, NULL, now()),
  ('employee-birthday-reminder', 'automation', 'workflow', 'published', false, 280, 'تذكير أعياد ميلاد الموظفين وإرسال التهنئة', 'HR & Recruitment', 'hr', 'مبتدئ', 'نسيان أعياد ميلاد الموظفين يُضعف الروح المعنوية وثقافة الاعتراف.', 'كل صباح يفحص الجدول → يكتشف أعياد الميلاد اليوم → يُرسل تهنئة للموظف وإشعارًا للمدير.', ARRAY['Google Sheets','Gmail','Slack'], ARRAY['إعداد جدول الموظفين مع عمود تاريخ الميلاد','كتابة قالب رسالة التهنئة','إضافة إشعار Slack للمدير المباشر'], ARRAY['اسم الموظف','البريد','تاريخ الميلاد','المدير'], 'بريد تهنئة للموظف + رسالة Slack للمدير لتقديم تهنئة شخصية.', ARRAY['أضف تاريخ ميلاد اليوم لموظف تجريبي','تأكد من وصول التهنئة بالبريد','فحص رسالة Slack للمدير'], ARRAY['إرسال تهنئة لموظف غادر الشركة'], ARRAY['إضافة بطاقة تهنئة رقمية','تنسيق احتفال افتراضي عند الوصول لـ 5 سنوات'], '25 دقيقة', 'Free', 'Scheduled (daily morning)', ARRAY['Read employee list','Filter today''s birthdays','Send greeting email','Notify manager on Slack'], 'لا تنسَ أي عيد ميلاد — أرسل تهنئة شخصية لكل موظف في يومه تلقائيًا.', 'بناء ثقافة عمل أكثر دفئًا وإنسانية دون أي جهد يومي.', ARRAY['Google Workspace','Slack Workspace'], '', 3, ARRAY['HR','موظفون','تهنئة','Slack','Google Sheets'], ARRAY['#HR','#automation','#n8n','#موارد_بشرية','#teambuilding'], 'الموارد البشرية', 'Schedule', ARRAY['Google Sheets','Gmail','Slack'], false, '', ARRAY['hr-onboarding-pack','attendance-alerts'], '{}', '{}', ARRAY['تنسيق تاريخ ميلاد غير موحد في الجدول','نسيان الموظفين الجدد'], 'آمن', 'تأكد من أن جدول الموظفين محدّث دائمًا بالموظفين الحاليين فقط.', true, '[]'::jsonb, NULL, now()),
  ('ecommerce-new-order-notify', 'automation', 'workflow', 'published', false, 290, 'إشعار فوري بالطلب الجديد للفريق والعميل', 'E-commerce Automation', 'operations', 'مبتدئ', 'الفريق يكتشف الطلبات الجديدة متأخرًا مما يُبطئ التجهيز والشحن.', 'Webhook طلب جديد → إشعار الفريق على Telegram/Slack → بريد تأكيد للعميل → تسجيل الطلب.', ARRAY['Webhook','Telegram Bot أو Slack','Gmail','Google Sheets'], ARRAY['ربط Webhook من منصة التجارة الإلكترونية','إعداد Telegram Bot أو Slack Incoming Webhook','إعداد قالب بريد التأكيد للعميل'], ARRAY['رقم الطلب','اسم العميل','المنتجات','المبلغ','العنوان'], 'إشعار للفريق + تأكيد للعميل + سجل الطلبات.', ARRAY['أرسل طلبًا تجريبيًا وتحقق من إشعار Telegram','تأكد من وصول بريد التأكيد للعميل','فحص التسجيل في Sheets'], ARRAY['إشعارات مكررة لنفس الطلب'], ARRAY['إضافة تتبع الشحن التلقائي','ربط بنظام المخزون لتحديث الكميات'], '30 دقيقة', 'Free', 'New order webhook', ARRAY['Send team notification','Send customer confirmation','Log order to Sheets'], 'كل طلب جديد يُشعِر الفريق فورًا ويُرسل تأكيدًا للعميل في ثوانٍ.', 'وقت استجابة أسرع + عميل سعيد يتلقى تأكيد فوري.', ARRAY['Telegram Bot Token أو Slack Workspace','Gmail'], '', 3, ARRAY['طلبات','تجارة','Telegram','إشعارات','Webhook'], ARRAY['#ecommerce','#automation','#n8n','#تجارة','#webhook'], 'التجارة الإلكترونية', 'Webhook', ARRAY['Webhook','Telegram','Gmail','Google Sheets'], false, '', ARRAY['inventory-low-stock-alert','abandoned-cart-reminder'], '{}', '{}', ARRAY['إغلاق Webhook بدون معالجة duplicates','قالب بريد يفتقر لبيانات الطلب'], 'آمن', 'أضف فحص معرف الطلب لتجنب إشعارات مكررة.', true, '[]'::jsonb, NULL, now());
