-- ══════════════════════════════════════════════════════════════════
-- v41 — IoT Lab — Projects (60 normal + 12 capstone) (iot_projects)
-- Run in: Supabase Dashboard → SQL Editor
-- FLAT type — the Project interface has no nested array-of-object fields
-- (features/components are plain string[]; wiringGuide/codeSnippet are
-- single strings) — matches the ai_glossary / ai_tools precedent.
-- ══════════════════════════════════════════════════════════════════

-- 1. Table
CREATE TABLE IF NOT EXISTS iot_projects (
  id              TEXT        PRIMARY KEY,                 -- = existing slug (e.g. 'led-blink') — keeps links intact
  portal_id       TEXT        NOT NULL DEFAULT 'iot-lab',
  content_type    TEXT        NOT NULL DEFAULT 'project',
  status          TEXT        NOT NULL DEFAULT 'published'
                              CHECK (status IN ('published','draft','archived')),
  featured        BOOLEAN     NOT NULL DEFAULT false,
  sort_order      INT         NOT NULL DEFAULT 0,
  title           TEXT        NOT NULL DEFAULT '',
  category        TEXT        NOT NULL DEFAULT '',
  difficulty      TEXT        NOT NULL DEFAULT 'سهل'
                              CHECK (difficulty IN ('سهل','متوسط','صعب','تخرج')),
  duration        TEXT        NOT NULL DEFAULT '',
  description     TEXT        NOT NULL DEFAULT '',
  features        TEXT[]      NOT NULL DEFAULT '{}',
  components      TEXT[]      NOT NULL DEFAULT '{}',
  wiring_guide    TEXT        NOT NULL DEFAULT '',
  code_snippet    TEXT        NOT NULL DEFAULT '',
  video_url       TEXT,
  simulator_link  TEXT,
  created_by      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_iot_projects_status     ON iot_projects (status);
CREATE INDEX IF NOT EXISTS idx_iot_projects_category   ON iot_projects (category);
CREATE INDEX IF NOT EXISTS idx_iot_projects_difficulty ON iot_projects (difficulty);

-- 2. Auto-update updated_at
CREATE OR REPLACE FUNCTION update_iot_projects_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_iot_projects_updated_at ON iot_projects;
CREATE TRIGGER trg_iot_projects_updated_at
  BEFORE UPDATE ON iot_projects
  FOR EACH ROW EXECUTE FUNCTION update_iot_projects_updated_at();

-- 3. RLS
ALTER TABLE iot_projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_published_iot_projects" ON iot_projects;
CREATE POLICY "public_read_published_iot_projects"
  ON iot_projects FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "admin_manage_iot_projects" ON iot_projects;
CREATE POLICY "admin_manage_iot_projects"
  ON iot_projects FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- Service role (API routes using createAdminClient) bypasses RLS — application
-- code verifies admin role before writes, matching the existing tables' convention.

-- ══════════════════════════════════════════════════════════════════
-- 4. Seed — the 72 existing projects (projectsDataPart1..4 — 60 normal + 12 capstone), SAME ids, status='published'.
--    Generated programmatically from the source .ts data files (zero transcription risk).
-- ══════════════════════════════════════════════════════════════════
INSERT INTO iot_projects (id, portal_id, content_type, status, featured, sort_order, title, category, difficulty, duration, description, features, components, wiring_guide, code_snippet, video_url, simulator_link, published_at)
VALUES
  ('led-blink', 'iot-lab', 'project', 'published', true, 0, 'وميض الليد الأول', 'أساسيات', 'سهل', '10 دقائق', 'تطبيقك الأول. تشغيل وإطفاء ضوء صغير كإثبات أنك تتحكم في عقل الأردوينو.', ARRAY['استخدام المخرجات الرقمية','التحكم بالزمن (delay)']::text[], ARRAY['Arduino Uno','LED','مقاومة 220 أوم']::text[], 'الموجب للدبوس 13، السالب للأرضي عبر مقاومة.', 'void setup() { pinMode(13, OUTPUT); }
void loop() { digitalWrite(13, HIGH); delay(1000); digitalWrite(13, LOW); delay(1000); }', NULL, 'https://wokwi.com/projects/305567166302257730', now()),
  ('traffic-light', 'iot-lab', 'project', 'published', true, 10, 'إشارة المرور المبرمجة', 'أساسيات', 'سهل', '20 دقيقة', 'بناء إشارة مرور ثلاثية الألوان تحاكي الواقع وتعتمد على التوقيت المنطقي.', ARRAY['التحكم المتسلسل','استخدام دبابيس متعددة']::text[], ARRAY['Arduino Uno','LED أحمر، أصفر، أخضر','3 مقاومات']::text[], 'الأحمر بـ 13، الأصفر بـ 12، الأخضر بـ 11.', 'void loop() {
  digitalWrite(13, HIGH); delay(5000);
  digitalWrite(13, LOW); digitalWrite(12, HIGH); delay(2000);
  digitalWrite(12, LOW); digitalWrite(11, HIGH); delay(5000);
  digitalWrite(11, LOW);
}', NULL, NULL, now()),
  ('smart-parking', 'iot-lab', 'project', 'published', true, 20, 'رادار الاصطفاف الذكي', 'الحساسات', 'متوسط', '40 دقيقة', 'نظام تحذير يقيس مسافة السيارة عن الجدار ويطلق صوتاً متسارعاً كلما اقتربت.', ARRAY['قياس المسافة الصوتية','إصدار نغمات بناءً على متغير','المنطق الشرطي']::text[], ARRAY['Arduino Uno','HC-SR04','Buzzer']::text[], 'Trig بـ 9، Echo بـ 10، البازر بـ 8.', 'long d = readUltrasonicDistance(9, 10);
if(d < 10) { tone(8, 1000, 100); delay(100); }
else if(d < 30) { tone(8, 1000, 100); delay(500); }', NULL, 'https://wokwi.com/projects/299313271173677576', now()),
  ('smart-plant-monitor', 'iot-lab', 'project', 'published', false, 30, 'مراقب النبتة الذكي', 'الزراعة', 'سهل', '30 دقيقة', 'جهاز صغير يغرس في حوض النبتة وينير باللون الأحمر إذا كانت التربة جافة جداً.', ARRAY['قراءة تناظرية','مقارنة القيم (Threshold)']::text[], ARRAY['Arduino Uno','حساس رطوبة تربة','LED أحمر']::text[], 'A0 لحساس التربة، دبوس 13 لليد.', 'if(analogRead(A0) > 800) digitalWrite(13, HIGH); else digitalWrite(13, LOW);', NULL, NULL, now()),
  ('motion-security-alarm', 'iot-lab', 'project', 'published', false, 40, 'إنذار الحركة الأمني', 'السلامة', 'متوسط', '30 دقيقة', 'جهاز إنذار يكتشف حركة الأشعة تحت الحمراء ويطلق سارينة صوتية قوية.', ARRAY['اكتشاف الحركة السلبية','الاستجابة الفورية']::text[], ARRAY['Arduino Uno','PIR Sensor','Active Buzzer']::text[], 'إشارة PIR بـ 2، البازر بـ 8.', 'if(digitalRead(2) == HIGH) { tone(8, 2000); } else { noTone(8); }', NULL, NULL, now()),
  ('lcd-menu-system', 'iot-lab', 'project', 'published', false, 50, 'شاشة التحكم التفاعلية', 'واجهات المستخدم', 'صعب', 'ساعة', 'بناء واجهة من عدة صفحات على شاشة LCD للتنقل بين إعدادات المشروع عبر الأزرار.', ARRAY['إدارة حالة النظام (State Machine)','استخدام بروتوكول I2C','منع الارتداد (Debounce)']::text[], ARRAY['Arduino Uno','LCD 16x2 I2C','3 أزرار']::text[], 'LCD I2C בـ A4 و A5، الأزرار בـ 2, 3, 4.', '// يعتمد على مكتبة LiquidCrystal_I2C
int menuPage = 0;
// كود إدارة الصفحات طويل، يرجى مراجعة الدرس', NULL, NULL, now()),
  ('servo-radar', 'iot-lab', 'project', 'published', false, 60, 'رادار الموجات الصوتية', 'روبوتات', 'متوسط', '45 دقيقة', 'يثبت حساس المسافة على محرك سيرفو ويدور يميناً ويساراً لمسح البيئة كأنه رادار حربي.', ARRAY['الدمج بين الحركة والقراءة','استخدام المصفوفات (Arrays)']::text[], ARRAY['Arduino Uno','Servo Motor','HC-SR04']::text[], 'السيرفو بـ 9، Trig بـ 10، Echo بـ 11.', 'for(int pos = 0; pos <= 180; pos++) { myServo.write(pos); delay(15); measureDistance(); }', NULL, NULL, now()),
  ('smart-fan-controller', 'iot-lab', 'project', 'published', false, 70, 'مروحة الحرارة الذكية', 'أتمتة المنزل', 'متوسط', '40 دقيقة', 'تقرأ الحرارة، وإذا تجاوزت 30 درجة، تبدأ المروحة بالدوران عبر ريلاي.', ARRAY['تحكم بالتيار المتردد/الأحمال العالية','قراءة رقمية معقدة (DHT11)']::text[], ARRAY['Arduino Uno','DHT11','Relay Module','مروحة صغيرة']::text[], 'DHT11 بـ 2، الريلاي بـ 7.', 'if(dht.readTemperature() > 30) digitalWrite(7, HIGH); else digitalWrite(7, LOW);', NULL, NULL, now()),
  ('esp32-web-server-led', 'iot-lab', 'project', 'published', false, 80, 'التحكم اللاسلكي من الجوال', 'إنترنت الأشياء', 'صعب', '50 دقيقة', 'اصنع شبكة واي فاي خاصة بك لتدخل إليها من الجوال وتضغط زراً يضيء مصباح الغرفة.', ARRAY['إنشاء Web Server','استخدام ESP32','كتابة كود HTML مبسط']::text[], ARRAY['ESP32','Relay Module','مصباح']::text[], 'الريلاي موصل بدبوس 2 في ESP32 (3.3V Logic).', 'server.on("/on", [](){ digitalWrite(2, HIGH); server.send(200, "text/html", "ON"); });', NULL, NULL, now()),
  ('bluetooth-robot-car', 'iot-lab', 'project', 'published', false, 90, 'سيارة البلوتوث الكلاسيكية', 'روبوتات', 'صعب', 'ساعتان', 'تجميع شاسيه سيارة والتحكم بها من خلال تطبيق على الجوال مثل سيارات الألعاب المتقدمة.', ARRAY['التجميع الميكانيكي','استقبال الأوامر التسلسلية (Serial)','قيادة محركين L298N']::text[], ARRAY['Arduino Uno','L298N','2 DC Motors','HC-05 Bluetooth']::text[], 'L298N بـ 8,9,10,11. البلوتوث بـ RX/TX. طاقة مشتركة.', 'if(Serial.available()){ char c = Serial.read(); if(c==''F'') goForward(); }', NULL, NULL, now()),
  ('obstacle-avoiding-robot', 'iot-lab', 'project', 'published', false, 100, 'السيارة ذاتية القيادة (تجنب العقبات)', 'روبوتات', 'صعب', 'ساعة ونصف', 'تتحرك السيارة للأمام، وعندما يستشعر السونار جداراً، تتوقف، ترجع للخلف، وتقرر الانعطاف.', ARRAY['القيادة الذاتية (Autonomous)','المنطق المركب']::text[], ARRAY['سيارة مجمعة مسبقاً','HC-SR04']::text[], 'إضافة حساس المسافة للسيارة السابقة.', 'if(dist < 20) { stop(); delay(500); goBack(); delay(500); turnRight(); }', NULL, NULL, now()),
  ('smart-door-lock-keypad', 'iot-lab', 'project', 'published', false, 110, 'الخزنة السرية (كلمة المرور)', 'أتمتة المنزل', 'صعب', 'ساعة', 'الباب لن يفتح إلا إذا كتبت الرقم السري 1234 على لوحة الأرقام. 3 أخطاء تطلق إنذاراً.', ARRAY['استقبال النصوص وتخزينها (Strings)','مقارنة المصفوفات','مكتبة Keypad']::text[], ARRAY['Arduino Uno','4x4 Keypad','Solenoid Lock','Relay']::text[], 'الكيباد للمنافذ 2-9، الريلاي للمنفذ 10.', 'if(key == ''#'') { checkPassword(); }', NULL, NULL, now()),
  ('rfid-attendance', 'iot-lab', 'project', 'published', false, 120, 'نظام تسجيل الحضور بالبطاقات', 'الأنظمة التجارية', 'صعب', 'ساعة وربع', 'مرر بطاقتك الجامعية الذكية، وسيتحقق النظام من صلاحيتك لفتح بوابة المختبر.', ARRAY['قراءة وتفكيك Hex','بروتوكول SPI','الأمان والتحقق']::text[], ARRAY['Arduino Uno','RC522 RFID','Servo','Buzzer']::text[], 'SPI (10,11,12,13) لـ RC522، والسيرفو يمثل البوابة.', 'if(uid == "A1B2C3D4") { openGate(); } else { soundAlarm(); }', NULL, NULL, now()),
  ('factory-temp-monitor', 'iot-lab', 'project', 'published', false, 130, 'مراقب المصنع (درجات الحرارة العالية)', 'الأنظمة الصناعية', 'متوسط', '45 دقيقة', 'استخدام حساس حرارة صناعي ذو مسبار مقاوم للماء لقياس حرارة سائل يغلي.', ARRAY['التعامل مع حساسات 1-Wire','دقة القياس']::text[], ARRAY['Arduino Uno','DS18B20','مقاومة 4.7K']::text[], 'الدبوس الأوسط من الحساس يوصل بالدبوس 2، مع مقاومة 4.7K بينه وبين VCC.', '// استخدام مكتبة DallasTemperature
sensors.requestTemperatures();
float t = sensors.getTempCByIndex(0);', NULL, NULL, now()),
  ('gas-leak-alarm', 'iot-lab', 'project', 'published', false, 140, 'مكتشف تسرب الغاز', 'السلامة', 'سهل', '25 دقيقة', 'وضع حساس غاز بجوار أسطوانة المطبخ، يطلق إنذاراً حاداً إذا زادت نسبة الغاز عن حد الأمان.', ARRAY['قراءة تناظرية','حساسات MQ']::text[], ARRAY['Arduino Uno','MQ-2 Gas Sensor','Buzzer']::text[], 'A0 لـ MQ-2، رقم 8 للبازر.', 'if(analogRead(A0) > 400) { tone(8, 2500); } else { noTone(8); }', NULL, NULL, now()),
  ('iot-weather-station', 'iot-lab', 'project', 'published', false, 150, 'محطة الطقس العالمية (IoT)', 'إنترنت الأشياء', 'تخرج', 'ساعتان', 'محطة أرصاد جوية تقيس الحرارة، الرطوبة، والضغط، وترسلها كل دقيقة لمنصة ThingSpeak لترسم جرافيكس حية.', ARRAY['HTTP GET','الرفع السحابي','I2C المتعدد']::text[], ARRAY['ESP32','BME280','DHT11']::text[], 'BME280 בـ I2C، و DHT11 בـ الدبوس 4.', 'http.begin(url + "&field1=" + String(t) + "&field2=" + String(p));
http.GET();', NULL, NULL, now()),
  ('smart-aquarium-monitor', 'iot-lab', 'project', 'published', false, 160, 'مراقب حوض الأسماك الذكي', 'تخرج', 'تخرج', 'ساعتان', 'تأكد من سلامة أسماكك، يقيس حرارة الماء (بمسبار مغمور)، ومستوى الماء، ويشغل إضاءة ليد في الليل.', ARRAY['الدمج المتعدد','التعامل مع بيئة مائية']::text[], ARRAY['Arduino Uno','DS18B20','Water Level Sensor','LDR','Relay']::text[], 'دمج بين مشاريع LDR، ومسبار الحرارة، والريلاي.', 'if(waterLevel < LOW_LIMIT) { sendAlert(); }', NULL, NULL, now()),
  ('line-follower-robot', 'iot-lab', 'project', 'published', false, 170, 'متتبع الخط السريع', 'روبوتات', 'صعب', 'ساعة ونصف', 'روبوت يسير على شريط أسود متعرج في الأرض بسرعة وموثوقية، ولا يخرج عن المسار.', ARRAY['التحكم الانعكاسي (Reflexive)','استخدام حساسين IR للحركة التناظرية']::text[], ARRAY['سيارة مجمعة','2 IR TCRT5000']::text[], 'الحساسات موجهة للأرض أسفل مقدمة السيارة.', 'if(L == 1 && R == 0) turnRight(); else if(L == 0 && R == 1) turnLeft();', NULL, NULL, now()),
  ('basic-circuit-no-code', 'iot-lab', 'project', 'published', false, 180, 'أول دائرة مغلقة (بدون كود)', 'أساسيات', 'سهل', '10 دقائق', 'إضاءة ليد باستخدام بطارية ومقاومة فقط لفهم قانون أوم بعيداً عن البرمجة.', ARRAY['التعرف على اللوحة التجريبية','فهم القطبية (Polarity)']::text[], ARRAY['Breadboard','LED','مقاومة 220 أوم','بطارية 9V مع وصلة']::text[], 'موجب البطارية لليد، سالب الليد للمقاومة ثم لسالب البطارية.', '// مشروع إلكتروني بحت، لا يوجد كود.', NULL, 'https://wokwi.com/projects/305567166302257730', now()),
  ('ultrasonic-meter', 'iot-lab', 'project', 'published', false, 190, 'شريط القياس الرقمي', 'الحساسات', 'متوسط', '30 دقيقة', 'قياس طول الأشياء كالمسطرة وعرض النتيجة بالسنتيمتر على شاشة LCD.', ARRAY['دمج حساس وشاشة','تحويل القياسات لنصوص']::text[], ARRAY['Arduino Uno','HC-SR04','LCD I2C']::text[], 'توصيل الشاشة بـ I2C، والحساس بدبابيس 9 و 10.', 'lcd.setCursor(0,0); lcd.print("Dist: "); lcd.print(distance); lcd.print(" cm");', NULL, NULL, now()),
  ('oled-sensor-dashboard', 'iot-lab', 'project', 'published', false, 200, 'لوحة تحكم مصغرة OLED', 'واجهات المستخدم', 'متوسط', '40 دقيقة', 'عرض درجة الحرارة، الرطوبة، والمسافة في شاشة واحدة بخطوط ناعمة وجميلة.', ARRAY['الرسم البيكسلي','ترتيب النصوص على الشاشة']::text[], ARRAY['Arduino Uno','OLED 0.96 I2C','DHT11']::text[], 'OLED بـ I2C (A4, A5)، DHT11 بدبوس 2.', 'display.setCursor(0,0); display.print("Temp: "); display.print(t); display.display();', NULL, NULL, now()),
  ('micropython-weather-station', 'iot-lab', 'project', 'published', false, 210, 'محطة طقس بايثون', 'برمجة متقدمة', 'صعب', '45 دقيقة', 'برمجة ESP32 بلغة بايثون لقراءة الحرارة وطباعتها.', ARRAY['استخدام Thonny','مكتبات MicroPython']::text[], ARRAY['ESP32','DHT11']::text[], 'توصيل DHT11 بأحد دبابيس الـ GPIO (مثلا 4).', 'import dht, machine; d = dht.DHT11(machine.Pin(4)); d.measure(); print(d.temperature())', NULL, NULL, now()),
  ('wireless-weather-station', 'iot-lab', 'project', 'published', false, 220, 'محطة الطقس الراديوية', 'الاتصالات اللاسلكية', 'صعب', 'ساعة وربع', 'الأردوينو الأول في الحديقة يقرأ الحرارة، ويرسلها بالراديو للأردوينو الثاني داخل المنزل ليعرضها على شاشة.', ARRAY['إرسال البيانات الهوائي','بروتوكول SPI المتقدم']::text[], ARRAY['2 Arduino Uno','2 NRF24L01','DHT11','LCD']::text[], 'NRF24 يعتمد على SPI ويحتاج طاقة 3.3V ثابتة جداً (يفضل استخدام موديول طاقة خاص به).', '// الإرسال:
radio.write(&temperature, sizeof(temperature));', NULL, NULL, now()),
  ('esp32-camera-concept', 'iot-lab', 'project', 'published', false, 230, 'بث الفيديو المباشر', 'الذكاء الاصطناعي', 'صعب', 'ساعة', 'استخدام لوحة ESP32-CAM ككاميرا مراقبة تبث الفيديو عبر الواي فاي على شبكتك المحلية.', ARRAY['التعامل مع الكاميرات','خوادم البث المباشر (Video Streaming)']::text[], ARRAY['ESP32-CAM','مبرمج FTDI']::text[], 'تحتاج لبرمجتها عبر FTDI لأنها لا تملك منفذ USB، بوضع GPIO0 مع الـ GND أثناء الرفع.', '// استخدم مثال CameraWebServer الجاهز من مكتبات ESP32.', NULL, NULL, now()),
  ('ai-object-detection', 'iot-lab', 'project', 'published', false, 240, 'الكاميرا الذكية (TinyML)', 'تخرج', 'تخرج', 'ساعتان', 'الكاميرا لا تصور فقط، بل تتعرف هل ما يمر أمامها إنسان أم قطة باستخدام نموذج تعلم آلي مصغر.', ARRAY['Edge AI','TensorFlow Lite for Microcontrollers']::text[], ARRAY['ESP32-CAM']::text[], 'مثل مشروع البث المباشر.', '// نموذج معقد يتطلب رفع ملفات الموديل (TFLite) للذاكرة.', NULL, NULL, now()),
  ('home-energy-monitor', 'iot-lab', 'project', 'published', false, 250, 'مراقب استهلاك الكهرباء', 'الأنظمة التجارية', 'صعب', 'ساعة وربع', 'استخدام حساس التيار غير التلامسي (SCT-013) لحساب كم واط يستهلك مكيف الغرفة.', ARRAY['التعامل مع التيار المتردد بأمان','الرياضيات المعقدة للتيار المتردد (RMS)']::text[], ARRAY['Arduino Uno','حساس SCT-013','مقاومات ومكثفات']::text[], 'الحساس يشبك حول أحد أسلاك الكهرباء (سلك واحد فقط وليس السلكين معاً) ويدخل لـ A0 عبر دائرة انحياز (Bias Circuit).', 'double Irms = emon1.calcIrms(1480); Serial.print(Irms*220.0); Serial.println(" Watts");', NULL, NULL, now()),
  ('solar-battery-monitor', 'iot-lab', 'project', 'published', false, 260, 'مراقب شحن الطاقة الشمسية', 'الطاقة', 'متوسط', '45 دقيقة', 'دائرة تحسب جهد بطارية 12V لتشغيل إنذار إذا اقتربت البطارية من النفاد ليلاً.', ARRAY['مقسم الجهد (Voltage Divider)','حسابات الفولتية الدقيقة']::text[], ARRAY['Arduino Uno','مقاومات 100K و 10K','بطارية 12V']::text[], 'مقسم جهد يقسم الـ 12V إلى حوالي 1V لتدخل آمنة لمنفذ A0.', 'float vout = (analogRead(A0) * 5.0) / 1024.0;
float vin = vout / (10000.0/(100000.0+10000.0));', NULL, NULL, now()),
  ('smart-irrigation-controller', 'iot-lab', 'project', 'published', false, 270, 'نظام الري الذكي للمزارع', 'تخرج', 'تخرج', 'ساعتان', 'يقرأ 4 حساسات تربة لمناطق مختلفة، ويتحكم بـ 4 صمامات مياه (Solenoid Valves) ليسقي كل منطقة حسب حاجتها.', ARRAY['إدارة المصفوفات والمناطق','الريلاي المتعدد']::text[], ARRAY['Arduino Uno','4 Soil Sensors','4 Channel Relay','4 Solenoid Valves 12V']::text[], 'الريلايات تقطع خط الـ 12V للصمامات.', 'for(int i=0; i<4; i++) { if(analogRead(sensors[i]) > 800) digitalWrite(valves[i], HIGH); }', NULL, NULL, now()),
  ('mini-greenhouse-automation', 'iot-lab', 'project', 'published', false, 280, 'الصوبة الزراعية المصغرة', 'الزراعة', 'صعب', 'ساعة ونصف', 'تتحكم بحرارة الصوبة، إذا زادت الحرارة تفتح مروحة، وإذا جفت التربة تضخ الماء، وإذا أظلمت تشغل ضوءاً صناعياً UV.', ARRAY['الدمج الكامل','إدارة الطاقة']::text[], ARRAY['Arduino Uno','DHT11','Soil Sensor','LDR','3 Relays']::text[], 'مشروع شامل لكل الأساسيات.', '// دمج كود المروحة والمضخة والإضاءة معاً باستخدام millis().', NULL, NULL, now()),
  ('smart-parking-gate', 'iot-lab', 'project', 'published', false, 290, 'بوابة المواقف الآلية', 'تخرج', 'تخرج', 'ساعتان', 'تستخدم الـ RFID للتعرف على سيارة المشترك، والسيرفو لفتح الحاجز، وشاشة ترحب به.', ARRAY['بناء منتج مصغر','التكامل بين الإدخال والإخراج']::text[], ARRAY['Arduino Uno','RC522 RFID','Servo','LCD I2C']::text[], 'الـ RFID في الـ SPI، السيرفو في 9، الشاشة I2C.', 'if(checkRFID()) { lcd.print("Welcome"); gateServo.write(90); delay(5000); gateServo.write(0); }', NULL, NULL, now()),
  ('people-counter', 'iot-lab', 'project', 'published', false, 300, 'عداد الزوار للمتاجر', 'الأنظمة التجارية', 'متوسط', '45 دقيقة', 'حساس ليزر (أو IR مزدوج) يحسب عدد الأشخاص الداخلين للمتجر ويعرضهم على شاشة.', ARRAY['منع الارتداد (Debouncing)','تحديد الاتجاه المنطقي']::text[], ARRAY['Arduino Uno','2 IR Obstacle Sensors','LCD I2C']::text[], 'حساسان يوضعان على إطار الباب، الفارق الزمني بين قطعهما يحدد هل الشخص داخل أم خارج.', 'if(sensor1 == LOW) { delay(50); if(sensor2 == LOW) { count++; } }', NULL, NULL, now()),
  ('water-tank-monitor', 'iot-lab', 'project', 'published', false, 310, 'مقياس خزان المياه اللاسلكي', 'تخرج', 'تخرج', 'ساعة ونصف', 'يوضع حساس مسافة أعلى الخزان ليقيس عمق الماء المتبقي، ويرسل النسبة المئوية للمنزل عبر واي فاي.', ARRAY['الرياضيات العكسية للمسافة والعمق','الشبكات']::text[], ARRAY['ESP32','Waterproof Ultrasonic JSN-SR04T']::text[], 'توصيل الحساس المقاوم للماء (لأن بخار الخزان يتلف الحساسات العادية).', 'float percentage = ((totalDepth - distance) / totalDepth) * 100.0;', NULL, NULL, now()),
  ('exam-hall-monitor', 'iot-lab', 'project', 'published', false, 320, 'مراقب قاعة الامتحانات (صامت)', 'الأنظمة التجارية', 'صعب', 'ساعة', 'نظام يقيس مستوى الضوضاء (الضجيج) وإذا تجاوز الحد، يضيء مصباحاً أحمر بصمت لتنبيه الطلاب دون إزعاج.', ARRAY['قراءة الصوت كمتغير تماثلي','الاستجابة الناعمة']::text[], ARRAY['Arduino Uno','Sound Sensor Module','LED Strip']::text[], 'حساس الصوت للمنفذ التناظري (A0) لتسجيل مستويات الديسبل التقريبية.', 'if(analogRead(A0) > 600) { warningLevel++; } // الخوارزمية تتجاهل الأصوات القصيرة كالسعال', NULL, NULL, now()),
  ('soil-moisture-dashboard', 'iot-lab', 'project', 'published', false, 330, 'مزرعتي في المتصفح', 'إنترنت الأشياء', 'صعب', 'ساعة', 'الـ ESP32 يقرأ رطوبة التربة ويعرضها بعداد جميل ومتحرك داخل صفحة ويب يستضيفها (Gauge Chart).', ARRAY['HTML/JS/CSS بداخل الـ C++','واجهات ديناميكية (AJAX)']::text[], ARRAY['ESP32','Soil Sensor']::text[], 'A0 לחساس.', '// الصفحة تتحدث عبر طلبات XMLHttpRequest دون إعادة تحميل الصفحة بالكامل.', NULL, NULL, now()),
  ('industrial-pump-monitor', 'iot-lab', 'project', 'published', false, 340, 'مراقب اهتزاز المضخات (IIoT)', 'الأنظمة الصناعية', 'تخرج', 'ساعة وربع', 'المصانع تعاني من تعطل المضخات. هذا المشروع يستخدم حساس اهتزاز يتنبأ بتلف المضخة قبل حدوثه.', ARRAY['تحليل الاهتزازات الأساسي','استخدام حساسات الصدمة (Piezo)']::text[], ARRAY['Arduino Uno','Vibration/Piezo Sensor SW-420']::text[], 'الحساس يلصق بجسم المحرك ويقرأ كنبضات رقمية أو تناظرية.', 'long vibrationCount = pulseIn(vibPin, HIGH);
if(vibrationCount > DANGER_LEVEL) { triggerAlarm(); }', NULL, NULL, now()),
  ('night-light', 'iot-lab', 'project', 'published', false, 350, 'الإنارة الليلية الأوتوماتيكية', 'أساسيات', 'سهل', '20 دقيقة', 'مثل مصابيح الشوارع، تضيء الغرفة بليد أبيض قوي فور إطفاء الأنوار.', ARRAY['استخدام حساس LDR','بناء دوائر النور التلقائية']::text[], ARRAY['Arduino Uno','LDR','LED أبيض قوي','ترانزستور TIP120']::text[], 'الترانزستور يستخدم لإعطاء تيار كافٍ لليد القوي من طاقة خارجية.', 'if(analogRead(A0) < 200) { analogWrite(9, 255); }', NULL, NULL, now()),
  ('morse-code-transmitter', 'iot-lab', 'project', 'published', false, 360, 'مرسل شفرة مورس', 'أساسيات', 'سهل', '25 دقيقة', 'يكتب الأردوينو رسالة استغاثة (SOS) عبر وميض الليد بنمط شفرة مورس العالمية.', ARRAY['الأنماط الزمنية الدقيقة','الحلقات التكرارية (For loops)']::text[], ARRAY['Arduino Uno','LED']::text[], 'مثل دائرة البلينك الأساسية.', 'void dot() { digitalWrite(13, HIGH); delay(200); digitalWrite(13, LOW); delay(200); } 
void dash() { digitalWrite(13, HIGH); delay(600); digitalWrite(13, LOW); delay(200); }', NULL, NULL, now()),
  ('reaction-time-game', 'iot-lab', 'project', 'published', false, 370, 'لعبة سرعة رد الفعل', 'ألعاب تفاعلية', 'متوسط', '45 دقيقة', 'يضيء الليد فجأة في وقت عشوائي، واللاعب الذي يضغط زره أولاً يفوز ويسجل نقطته على الشاشة.', ARRAY['دالة random()','المقاطعات (Interrupts)','التسجيل الزمني']::text[], ARRAY['Arduino Uno','2 أزرار ضغاطة','LED','LCD I2C']::text[], 'الأزرار بدبابيس المقاطعة 2 و 3.', 'delay(random(2000, 5000)); digitalWrite(led, HIGH); startTime = millis();', NULL, NULL, now()),
  ('music-box', 'iot-lab', 'project', 'published', false, 380, 'صندوق الموسيقى المبرمج', 'الخرج والتنبيه', 'متوسط', '30 دقيقة', 'الأردوينو يعزف مقطوعة موسيقية شهيرة باستخدام مصفوفات للترددات (النوتات) ومصفوفات للزمن.', ARRAY['التعامل مع المصفوفات المزدوجة','استخدام tone()']::text[], ARRAY['Arduino Uno','Passive Buzzer']::text[], 'البازر بالدبوس 8 مع مقاومة 100 أوم.', 'int melody[] = { NOTE_C4, NOTE_G3, NOTE_G3, NOTE_A3, NOTE_G3, 0, NOTE_B3, NOTE_C4 };', NULL, NULL, now()),
  ('sun-tracker', 'iot-lab', 'project', 'published', false, 390, 'متتبع أشعة الشمس (Solar Tracker)', 'الطاقة', 'صعب', 'ساعة ونصف', 'خلية شمسية صغيرة مثبتة على سيرفو موتور. حساسين LDR يقرآن الضوء لتوجيه السيرفو دائماً نحو الشمس.', ARRAY['حلقة التغذية العكسية','مقارنة الحساسات التناظرية']::text[], ARRAY['Arduino Uno','Servo','2 LDR','خلية شمسية 5V']::text[], 'حساسي الـ LDR كعيني الروبوت يميناً ويساراً.', 'if(leftLDR > rightLDR + 50) { pos++; servo.write(pos); }', NULL, NULL, now()),
  ('digital-dice', 'iot-lab', 'project', 'published', false, 400, 'النرد الرقمي الذكي', 'ألعاب تفاعلية', 'متوسط', '40 دقيقة', 'اضغط على الزر لتهتز 7 ليدات مصفوفة كحجر النرد لتتوقف على رقم عشوائي من 1 لـ 6.', ARRAY['برمجة الأنماط المرئية','توليد أرقام عشوائية بتغذية تناظرية']::text[], ARRAY['Arduino Uno','7 LEDs','زر']::text[], 'توصيل 7 ليدات بمنافذ من 2 لـ 8 وتوزيعها بشكل نرد على البريد بورد.', 'randomSeed(analogRead(0)); int roll = random(1, 7); showDice(roll);', NULL, NULL, now()),
  ('clap-switch', 'iot-lab', 'project', 'published', false, 410, 'مفتاح التصفيق', 'أتمتة المنزل', 'متوسط', '35 دقيقة', 'صفق بيديك مرة لتشغيل المصباح، وصفق مرة أخرى لإطفائه باستخدام حساس الصوت.', ARRAY['حفظ حالة النظام (Toggle State)','تصفية الضوضاء القصيرة']::text[], ARRAY['Arduino Uno','Sound Sensor','Relay']::text[], 'حساس الصوت للمنفذ الرقمي.', 'if(soundDetected && (millis() - lastClap > 200)) { ledState = !ledState; }', NULL, NULL, now()),
  ('staircase-lights', 'iot-lab', 'project', 'published', false, 420, 'إضاءة الدرج التتابعية', 'أتمتة المنزل', 'صعب', 'ساعة', 'عندما تضع قدمك على أول درجة في السلم، تضيء الدرجات واحدة تلو الأخرى بشكل متدرج (Fade) للأعلى.', ARRAY['التحكم بشرائط الليد الذكية','المؤثرات البصرية']::text[], ARRAY['Arduino Uno','WS2812B LED Strip','2 PIR Sensors']::text[], 'حساس PIR في أسفل الدرج وآخر في أعلاه.', 'for(int i=0; i<NUM_LEDS; i++) { leds[i]=CRGB::White; FastLED.show(); delay(100); }', NULL, NULL, now()),
  ('lie-detector', 'iot-lab', 'project', 'published', false, 430, 'كاشف الكذب البسيط', 'تجارب علمية', 'متوسط', '45 دقيقة', 'يقيس مدى تعرق الجلد الذي يتغير عند التوتر وتغيير مقاومة الجسم. يضيء ليدات تدريجياً حسب مستوى التوتر.', ARRAY['قراءة المقاومة البيولوجية','تحليل التغيرات الدقيقة']::text[], ARRAY['Arduino Uno','أسلاك بنهايات معدنية','ليدات','مقاومة 1 ميجا أوم']::text[], 'السلك المعدني يلف حول إصبعين. الدائرة تشبه مقسم الجهد ولكن جسم الإنسان هو المقاومة المتغيرة.', 'int sweatLevel = analogRead(A0); int mapped = map(sweatLevel, 0, 1023, 0, 5);', NULL, NULL, now()),
  ('rfid-jukebox', 'iot-lab', 'project', 'published', false, 440, 'مشغل الموسيقى بالبطاقات الذكية', 'ألعاب تفاعلية', 'صعب', 'ساعة وربع', 'ضع بطاقة بشخصية معينة فوق הקارئ، ليعزف الأردوينو المقطوعة الموسيقية الخاصة بتلك الشخصية.', ARRAY['ربط المعرفات (UIDs) بأحداث معقدة','تنظيم الكود']::text[], ARRAY['Arduino Uno','RC522 RFID','Buzzer أو MP3 DFPlayer']::text[], 'دمج بين درس RFID والـ Music Box.', 'if(uid == "CARD_MARIO") { playMarioTheme(); } else if(uid == "CARD_ZELDA") { playZeldaTheme(); }', NULL, NULL, now()),
  ('smart-trash-can', 'iot-lab', 'project', 'published', false, 450, 'سلة المهملات الذكية', 'الروبوتات والميكانيكا', 'متوسط', '45 دقيقة', 'مجرد أن تقرب يدك من السلة، يفتح الغطاء آلياً عبر السيرفو موتور ويغلق بعد 3 ثوانٍ.', ARRAY['بناء مجسم ميكانيكي','التحكم الزمني لعدم إغلاق الغطاء على اليد']::text[], ARRAY['Arduino Uno','Servo Motor','HC-SR04']::text[], 'حساس المسافة في الواجهة، السيرفو مثبت بالمفصلة الخلفية للغطاء.', 'if(distance < 15) { servo.write(90); delay(3000); } else { servo.write(0); }', NULL, NULL, now()),
  ('weather-clock', 'iot-lab', 'project', 'published', false, 460, 'ساعة الطقس المكتبية', 'شاشات ووقت', 'صعب', 'ساعة ونصف', 'شاشة OLED تعرض الوقت الفعلي بدقة باستخدام RTC، ودرجة حرارة الغرفة الحالية بخطوط جميلة وأيقونات.', ARRAY['الدمج بين I2C Devices','رسم أيقونات (Bitmap) على OLED']::text[], ARRAY['Arduino Uno','OLED 0.96','RTC DS3231','DHT11']::text[], 'شريحتان تعملان على نفس سلكي I2C (A4 و A5) كل منهما بعنوان مختلف.', 'display.drawBitmap(0, 0, sunIcon, 16, 16, WHITE); display.print(rtc.now().hour());', NULL, NULL, now()),
  ('color-sorting-machine', 'iot-lab', 'project', 'published', false, 470, 'ماكينة فرز الألوان الآلية', 'تخرج', 'تخرج', 'ساعتان', 'حساس ألوان يقرأ لون الحلوى أو الكرات، وسيرفوان يتحركان لإسقاط كل لون في الكوب المخصص له.', ARRAY['تحليل الألوان RGB','الحركة الميكانيكية المزدوجة والمزامنة']::text[], ARRAY['Arduino Uno','TCS3200 Color Sensor','2 Servo Motors']::text[], 'حساس الألوان يتطلب 4 دبابيس للتحكم بالمرشحات الترددية.', 'if(R > G && R > B) { dropInRedCup(); } else if(G > R && G > B) { dropInGreenCup(); }', NULL, NULL, now()),
  ('blind-stick', 'iot-lab', 'project', 'published', false, 480, 'عصا المكفوفين الذكية', 'تكنولوجيا مساعدة', 'متوسط', '45 دقيقة', 'عصا تهتز وتصدر صوتاً كلما اقتربت من حاجز، سرعة الاهتزاز تزيد مع الاقتراب.', ARRAY['الترجمة الفيزيائية للمسافة (Haptic Feedback)']::text[], ARRAY['Arduino Nano','HC-SR04','Vibration Motor','Buzzer','بطارية صغيرة']::text[], 'المحرك الهزاز يجب أن يوصل بترانزستور وليس بدبوس الأردوينو مباشرة.', 'int vibSpeed = map(distance, 5, 100, 255, 0); analogWrite(vibPin, vibSpeed);', NULL, NULL, now()),
  ('laser-tripwire', 'iot-lab', 'project', 'published', false, 490, 'ليزر الإنذار كالأفلام (Tripwire)', 'السلامة', 'سهل', '30 دقيقة', 'شعاع ليزر موجه نحو حساس LDR. إذا عبر أحد وقطع شعاع الليزر، تنطلق السارينة ولا تتوقف حتى تضغط زراً مخفياً.', ARRAY['آلية القفل (Latching Alarm)','المقاييس الدقيقة للضوء']::text[], ARRAY['Arduino Uno','Laser Module','LDR','Buzzer','زر ضغاط']::text[], 'الليزر يشغل بـ 5V مباشرة مقابل حساس הـ LDR.', 'if(analogRead(ldrPin) < 100) { alarmTriggered = true; }
if(alarmTriggered) { tone(buzzer, 3000); }', NULL, NULL, now()),
  ('esp32-discord-bot', 'iot-lab', 'project', 'published', false, 500, 'بوت ديسكورد ينبهك لحرارة الغرفة', 'إنترنت الأشياء', 'تخرج', 'ساعة ونصف', 'لوحة ESP32 ترسل رسالة إلى سيرفر Discord الخاص بك متضمنة درجة حرارة غرفتك إذا زادت عن 30 درجة.', ARRAY['استخدام Webhooks','تشفير HTTPS وشهادات SSL']::text[], ARRAY['ESP32','DHT11']::text[], 'مثل مشاريع ESP32 السابقة.', 'HTTPClient http; http.begin("https://discord.com/api/webhooks/...", root_ca);', NULL, NULL, now()),
  ('morse-code-decoder', 'iot-lab', 'project', 'published', false, 510, 'مترجم شفرة مورس (مستقبل)', 'برمجة متقدمة', 'صعب', 'ساعة وربع', 'استخدم زراً للضغط بنمط مورس (طويل وقصير)، وسيقوم الأردوينو بطباعة الحرف بالإنجليزية على الشاشة.', ARRAY['حساب أزمنة الضغط بدقة (Pulse Width)','أشجار البحث البرمجية']::text[], ARRAY['Arduino Uno','زر ضغاط','LCD I2C']::text[], 'زر على دبوس 2.', '// يعتمد على حساب millis() أثناء ضغط الزر وتركه لتحديد ما إذا كان ''نقطة'' أم ''شرطة''.', NULL, NULL, now()),
  ('automatic-pet-feeder', 'iot-lab', 'project', 'published', false, 520, 'مُطعم الحيوانات الأليفة الآلي', 'أتمتة المنزل', 'صعب', 'ساعة ونصف', 'كل 12 ساعة، يتحرك سيرفو لفتح باب خزان الطعام الجاف للقطط لمدة ثانيتين ثم يغلقه.', ARRAY['التعامل مع الفترات الزمنية الطويلة جداً بأمان','تجنب أخطاء overflow']::text[], ARRAY['Arduino Uno','Servo Motor','RTC DS3231']::text[], 'الـ RTC ضروري هنا لتجنب أخطاء الـ millis() بعد أسابيع من التشغيل المستمر.', 'if(now.hour() == 8 || now.hour() == 20) { feedPet(); delay(60000); // لمنع التكرار في نفس الدقيقة }', NULL, NULL, now()),
  ('drone-leveler', 'iot-lab', 'project', 'published', false, 530, 'حفظ توازن الدرون بمستشعر الزوايا (MPU6050)', 'الروبوتات', 'تخرج', 'ساعتان', 'اقرأ ميلان اللوحة (Pitch, Roll) عبر حساس الجايروسكوب، واجعل سيرفو يتحرك بعكس الميلان ليبقى متوازناً كأسطح السفن.', ARRAY['رياضيات الجايرو ومقاييس التسارع','استخدام فلتر الكالمان أو المكمل (Complementary Filter)']::text[], ARRAY['Arduino Uno','MPU6050','Servo Motor']::text[], 'MPU6050 يعمل בـ I2C (A4, A5) ויجب تزويده بـ 3.3V أو 5V حسب الموديول.', '// استخدام مكتبة MPU6050
int angle = map(accelX, -17000, 17000, 0, 180); servo.write(angle);', NULL, NULL, now()),
  ('bluetooth-home-automation', 'iot-lab', 'project', 'published', false, 540, 'المنزل الذكي بالبلوتوث', 'أتمتة المنزل', 'متوسط', 'ساعة', 'تطبيق جوال يرسل أوامر للبلوتوث لتشغيل أو إطفاء 4 مصادر مختلفة للإضاءة في الغرفة.', ARRAY['بناء واجهة جوال بسيطة (عبر MIT App Inventor)','استقبال الأوامر ومعالجتها']::text[], ARRAY['Arduino Uno','HC-05','4 Channel Relay Module']::text[], 'الريلاي يوصل بـ 4 منافذ ديجيتال. البلوتوث بـ RX و TX.', 'if(command == ''A'') digitalWrite(relay1, HIGH); else if(command == ''a'') digitalWrite(relay1, LOW);', NULL, NULL, now()),
  ('water-quality-tester', 'iot-lab', 'project', 'published', false, 550, 'مختبر جودة المياه', 'تجارب علمية', 'متوسط', 'ساعة', 'قياس نقاء الماء (TDS - Total Dissolved Solids) لمعرفة نسبة الأملاح وتحديد هل الماء صالح للشرب.', ARRAY['تحويل القراءات التناظرية لقيم علمية دقيقة (PPM)']::text[], ARRAY['Arduino Uno','TDS Sensor Meter','LCD I2C']::text[], 'مخرج TDS التناظري لمنفذ A0.', 'float tdsValue=(133.42*compensationVolatge*compensationVolatge*compensationVolatge - 255.86*compensationVolatge*compensationVolatge + 857.39*compensationVolatge)*0.5;', NULL, NULL, now()),
  ('pomodoro-timer', 'iot-lab', 'project', 'published', false, 560, 'مؤقت بومودورو للإنتاجية', 'شاشات ووقت', 'متوسط', '45 دقيقة', 'مؤقت يعد تنازلياً لـ 25 دقيقة للدراسة، ثم يطلق نغمة ويبدأ عداد 5 دقائق للاستراحة، وتظهر الأرقام على شاشة 7-Segment.', ARRAY['استخدام شاشات 7-Segment','حساب الوقت المتبقي']::text[], ARRAY['Arduino Uno','4-Digit 7-Segment Display (TM1637)','Buzzer']::text[], 'وحدة TM1637 تحتاج دبابيس CLK و DIO فقط للتحكم بـ 4 أرقام.', 'display.showNumberDecEx(timeDisplay, 0b01000000, true, 4, 0);', NULL, NULL, now()),
  ('gps-tracker', 'iot-lab', 'project', 'published', false, 570, 'جهاز التتبع الملاحي (GPS)', 'تخرج', 'تخرج', 'ساعة ونصف', 'شاشة صغيرة تعرض خطوط الطول والعرض الحالية وسرعة حركتك وارتفاعك عن سطح البحر من خلال الأقمار الصناعية.', ARRAY['فك تشفير جمل NMEA','استخدام مكتبة TinyGPS++']::text[], ARRAY['Arduino Uno','NEO-6M GPS Module','OLED 0.96']::text[], 'الـ GPS يتصل عبر Serial Software، (TX من الـ GPS لـ RX وهمي في الأردوينو).', 'while (gpsSerial.available() > 0) { gps.encode(gpsSerial.read()); }
if (gps.location.isUpdated()) { Serial.println(gps.location.lat()); }', NULL, NULL, now()),
  ('plant-watering-robot', 'iot-lab', 'project', 'published', false, 580, 'روبوت ري الزرع المتحرك', 'تخرج', 'تخرج', '3 ساعات', 'روبوت يسير على خط بين الأحواض، يتوقف عند كل حوض، يقرأ رطوبته، يضخ الماء إن لزم، ثم يكمل طريقه للحوض التالي.', ARRAY['الدمج العميق للمسارات','إدارة الطاقة المشتركة للروبوت والمضخة']::text[], ARRAY['سيارة مجمعة','Line Tracking Sensors','Water Pump','Soil Sensor','Servo']::text[], 'السيرفو يُنزل حساس الرطوبة للتربة ثم يرفعه ليتحرك الروبوت.', '// يعتمد على State Machine كاملة: السير، التوقف، الفحص، الضخ، الاستكمال.', NULL, NULL, now()),
  ('gesture-controlled-car', 'iot-lab', 'project', 'published', false, 590, 'سيارة يتم التحكم بها بإيماءات اليد', 'تخرج', 'تخرج', 'ساعتان', 'ارتدِ قفازاً به حساس ميلان ومرسل لاسلكي. عندما تميل يدك للأمام، تسير السيارة للأمام (سحر حقيقي).', ARRAY['الاتصال اللاسلكي بين جهازين (Master/Slave)','الجايروسكوب']::text[], ARRAY['2 Arduino Nano','MPU6050','2 NRF24L01','سيارة مجمعة']::text[], 'قفاز (إرسال): MPU + NRF + بطارية. السيارة (استقبال): NRF + L298N.', 'if(pitch > 30) { sendCommand(''F''); } else if(pitch < -30) { sendCommand(''B''); }', NULL, NULL, now()),
  ('heart-rate-monitor', 'iot-lab', 'project', 'published', false, 600, 'مقياس نبضات القلب', 'تجارب علمية', 'متوسط', 'ساعة', 'ضع إصبعك على الحساس الضوئي، ليحسب الأردوينو نبضات قلبك في الدقيقة ويرسمها على شاشة OLED كالمستشفيات.', ARRAY['التعامل مع الإشارات البيولوجية (PPG)','استخراج القمم (Peaks) من الموجات']::text[], ARRAY['Arduino Uno','Pulse Sensor','OLED 0.96']::text[], 'Pulse Sensor يوصل لـ A0.', '// مكتبة PulseSensorPlayground تسهل المهمة
int myBPM = pulseSensor.getBeatsPerMinute();', NULL, NULL, now()),
  ('rfid-parking-system', 'iot-lab', 'project', 'published', false, 610, 'نظام إدارة المواقف الآلي', 'الأنظمة التجارية', 'صعب', 'ساعة ونصف', 'الشاشة تعرض ''المواقف ممتلئة'' إذا دخلت 5 سيارات. الـ RFID يفتح الباب ويزيد العداد، وعند الخروج ينقص العداد.', ARRAY['إدارة المتغيرات الكلية','المنطق المزدوج (دخول/خروج)']::text[], ARRAY['Arduino Uno','RC522 RFID','Servo','LCD','IR Sensor (للتأكد من مرور السيارة)']::text[], 'الـ IR يوضع بعد البوابة للتأكد أن السيارة عبرت ليتم إغلاق البوابة.', 'if(carEntered && parkingSpots > 0) { parkingSpots--; updateDisplay(); }', NULL, NULL, now()),
  ('smart-trash-sorting', 'iot-lab', 'project', 'published', false, 620, 'سلة فرز النفايات الذكية', 'تخرج', 'تخرج', 'ساعتان', 'حساس للرطوبة والكهرباء يختبر القطعة الملقاة، إذا كانت معدناً يوجهها يميناً، وإذا كانت بلاستيك يوجهها يساراً.', ARRAY['الاستشعار المادي (Capacitive/Inductive)','الفرز الميكانيكي']::text[], ARRAY['Arduino Uno','Inductive Proximity Sensor','Servo Motor']::text[], 'حساس التقارب المعدني الصناعي (يعمل بـ 12V ويحتاج مقسم جهد لإشارته).', 'if(metalDetected) { servo.write(45); delay(1000); drop(); }', NULL, NULL, now()),
  ('voice-controlled-lights', 'iot-lab', 'project', 'published', false, 630, 'التحكم الصوتي بالأنوار', 'أتمتة المنزل', 'صعب', 'ساعة ونصف', 'استخدام موديول التعرف على الصوت (Elechouse Voice Recognition) لبرمجة أوامر مثل ''إضاءة'' و ''إطفاء''.', ARRAY['تدريب النماذج الصوتية','التعامل مع الأوامر النصية']::text[], ARRAY['Arduino Uno','Voice Recognition Module V3','Relay']::text[], 'يتواصل عبر Software Serial (الـ RX و TX).', 'int ret = myVR.recognize(buf, 50);
if(ret>0 && buf[1] == ON_RECORD) { digitalWrite(relay, HIGH); }', NULL, NULL, now()),
  ('electronic-piano', 'iot-lab', 'project', 'published', false, 640, 'البيانو الإلكتروني', 'ألعاب تفاعلية', 'متوسط', '45 دقيقة', '7 أزرار تشبه أصابع البيانو، كل زر يعزف نوتة موسيقية مختلفة على البازر. وإذا ضغطت زرين معاً يعزف النوتة الأعلى.', ARRAY['قراءة دبابيس متعددة باستمرار','التحكم بترددات الصوت العالية']::text[], ARRAY['Arduino Uno','7 Push Buttons','Passive Buzzer']::text[], 'كل زر موصل بدبوس ديجيتال بوضعية INPUT_PULLUP.', 'if(!digitalRead(2)) tone(8, NOTE_C4); else if(!digitalRead(3)) tone(8, NOTE_D4); else noTone(8);', NULL, NULL, now()),
  ('air-quality-monitor', 'iot-lab', 'project', 'published', false, 650, 'شاشة جودة الهواء (AQI)', 'الأنظمة التجارية', 'صعب', 'ساعة', 'جهاز يقيس مستوى الغبار (PM2.5) والغازات في الغرفة وينير باللون الأخضر/الأصفر/الأحمر ليدل على جودة الهواء.', ARRAY['قياس الجسيمات الدقيقة','معالجة الخرج اللوني']::text[], ARRAY['Arduino Uno','Dust Sensor (GP2Y1014AU0F)','MQ-135','RGB LED']::text[], 'حساس الغبار يتطلب دبوساً ديجيتال لتشغيل الليد الداخلي، ودبوساً تناظرياً للقراءة.', 'digitalWrite(ledPower, LOW); delayMicroseconds(280); voMeasured = analogRead(measurePin);', NULL, NULL, now()),
  ('esp32-telegram-bot', 'iot-lab', 'project', 'published', false, 660, 'إنذار عبر رسالة تليجرام', 'إنترنت الأشياء', 'تخرج', 'ساعة وربع', 'عندما يفتح أحدهم باب غرفتك، يرسل الـ ESP32 رسالة نصية فورية لتطبيق التليجرام في جوالك.', ARRAY['التعامل مع Telegram Bots API','معالجة HTTPS Requests']::text[], ARRAY['ESP32','Magnetic Door Sensor (Reed Switch)']::text[], 'حساس الباب يعمل كزر عادي تماماً (مغناطيس يغلق الدائرة).', 'bot.sendMessage(CHAT_ID, "ALERT: Door Opened!", "");', NULL, NULL, now()),
  ('smart-mirror-clock', 'iot-lab', 'project', 'published', false, 670, 'المرآة السحرية (ساعة مخفية)', 'تخرج', 'تخرج', 'ساعتان', 'خلف زجاج عاكس (Two-way mirror)، نضع شاشات 7-Segment حمراء قوية و ESP32 يجلب الوقت من الإنترنت.', ARRAY['صناعة الديكور الذكي','تزامن وقت الشبكة (NTP)']::text[], ARRAY['ESP32','MAX7219 Dot Matrix أو 7-Segment كبير','زجاج عاكس']::text[], 'MAX7219 يتواصل عبر SPI.', 'configTime(gmtOffset_sec, daylightOffset_sec, ntpServer); // جلب الوقت من الويب بدون RTC', NULL, NULL, now()),
  ('automatic-hand-sanitizer', 'iot-lab', 'project', 'published', false, 680, 'موزع المعقم الآلي', 'الأنظمة التجارية', 'متوسط', '45 دقيقة', 'مرر يدك تحت الجهاز ليضخ الكحول أو الصابون لمدة ثانية واحدة باستخدام حساس مسافة ومضخة صغيرة.', ARRAY['الاستخدام العملي للسلامة','الموثوقية']::text[], ARRAY['Arduino Uno','IR Obstacle Sensor','Mini Water Pump 5V','ترانزستور TIP120']::text[], 'استخدم الترانزستور لتشغيل المضخة لأن الريلاي الميكانيكي يتلف من كثرة الاستخدام المستمر هنا.', 'if(digitalRead(irPin) == LOW) { digitalWrite(pump, HIGH); delay(1000); digitalWrite(pump, LOW); delay(2000); }', NULL, NULL, now()),
  ('color-mixer-lamp', 'iot-lab', 'project', 'published', false, 690, 'مصباح دمج الألوان', 'أساسيات', 'سهل', '30 دقيقة', '3 مقاومات متغيرة (Potentiometers)، كل واحدة تتحكم بلون (أحمر، أخضر، أزرق) في ليد RGB لتصنع 16 مليون لون مختلف.', ARRAY['PWM بـ 3 قنوات','التفاعل البشري']::text[], ARRAY['Arduino Uno','RGB LED','3 Potentiometers','3 مقاومات 220 أوم']::text[], 'دبابيس A0, A1, A2 للمقاومات المتغيرة. دبابيس 9, 10, 11 (PWM) لأرجل הـ RGB.', 'analogWrite(9, map(analogRead(A0), 0, 1023, 0, 255));', NULL, NULL, now()),
  ('flame-detector', 'iot-lab', 'project', 'published', false, 700, 'نظام إطفاء الحريق للروبوت', 'تخرج', 'تخرج', 'ساعة ونصف', 'روبوت إطفاء يدور باحثاً عن مصدر للضوء المخصص للنار (Flame Sensor IR)، ثم يقترب ويضخ الماء عليه.', ARRAY['البحث والتتبع','الدمج بين الكشف والإطفاء']::text[], ARRAY['Arduino Uno','Flame Sensor','Water Pump','سيارة مجمعة']::text[], 'Flame Sensor يقرأ الأشعة تحت الحمراء الصادرة من النار كقيمة تناظرية.', 'if(analogRead(flamePin) < 300) { stopCar(); pumpWater(); }', NULL, NULL, now()),
  ('cnc-drawing-machine', 'iot-lab', 'project', 'published', false, 710, 'آلة الرسم الآلية (Mini CNC)', 'تخرج', 'تخرج', 'مفتوح', 'استخدام محركات طابعة و CD قديمة (Stepper Motors) لصنع آلة ترسم صوراً وأحرفاً على الورق بواسطة قلم.', ARRAY['فك تشفير G-Code','الهندسة العكسية','التحكم الميكانيكي الدقيق بـ 3 محاور']::text[], ARRAY['Arduino Uno','CNC Shield','2 DVD Drive Steppers','Servo (لرفع القلم)']::text[], 'استخدام درع الـ CNC وتركيب درايفرات A4988 عليه وتنزيل كود جاهز مثل GRBL.', '// هذا المشروع يعتمد على تحميل برنامج (Firmware) كامل مثل GRBL إلى الأردوينو لتفسير ملفات الرسم.', NULL, NULL, now());
